import { Word } from './interfaces'

export const words: Word[] = [
  { kanji: '始めましょう', word: 'はじめましょう', translation: 'Vamos a empezar' },
  { kanji: '終わりましょう', word: 'おわりましょう', translation: 'Vamos a terminar' },
  { kanji: '休みましょう', word: 'やすみましょう', translation: 'Vamos a descansar' },
  { kanji: 'もう 一度', word: 'もういちど', translation: 'De nuevo' },
  { kanji: '名前', word: 'なまえ', translation: 'Nombre' },
  { kanji: '試験', word: 'しけん', translation: 'Examen' },
  { kanji: '宿題', word: 'しゅくだい', translation: 'Tarea' },
  { kanji: '質問', word: 'しつもん', translation: 'Pregunta' },
  { kanji: '答え', word: 'こたえ', translation: 'Respuesta' },
  { kanji: '例', word: 'れい', translation: 'Ejemplo' },
  { kanji: '分かりますか', word: 'わかりますか', translation: '¿Entendiste?' },
  { kanji: '分かります', word: 'わかります', translation: 'Entiendo' },
  { kanji: '分かりません', word: 'わかりません', translation: 'No entiendo.' },
  { word: 'けっこうです', translation: 'Está bien' },
  { kanji: '駄目です', word: 'だめです', translation: 'Está mal' },
  { word: 'おはようございます', translation: 'Buenos Días' },
  { word: 'こんにちは', translation: 'Hola', particles: { は: [4] } },
  { word: 'こんばんは', translation: 'Buenas noches', particles: { は: [4] } },
  { kanji: 'お休みなさい', word: 'おやすみなさい', translation: 'Buenas noches (dormir)' },
  { word: 'さようなら', translation: 'Adiós' },
  { word: 'ありがとうございます', translation: 'Muchas gracias' },
  { word: 'すみません', translation: 'Disculpe' },
  { kanji: 'お願いします', word: 'おねがいします', translation: 'Por favor' },
  { kanji: '零', word: 'れい', translation: '0' },
  { kanji: '零', word: 'ゼロ', translation: '0' },
  { kanji: '一', word: 'いち', translation: '1' },
  { kanji: '二', word: 'に', translation: '2' },
  { kanji: '三', word: 'さん', translation: '3' },
  { kanji: '四', word: 'よん', translation: '4' },
  { kanji: '午', word: 'ご', translation: '5' },
  { kanji: '六', word: 'ろく', translation: '6' },
  { kanji: '七', word: 'なな', translation: '7' },
  { kanji: '八', word: 'はち', translation: '8' },
  { kanji: '九', word: 'きゅう', translation: '9' },
  { kanji: '十', word: 'じゅう', translation: '10' },
  { kanji: '私', word: 'わたし', translation: 'Yo' },
  { kanji: '私達', word: 'わたしたち', translation: 'Nosotros' },
  { kanji: '貴方', word: 'あなた', translation: 'Tu' },
  { kanji: 'あの人', word: 'あのひと', translation: 'Aquella Persona' },
  { kanji: 'あの方', word: 'あのかた', translation: 'Aquella Persona (formal)' },
  { kanji: '皆さん', word: 'みなさん', translation: 'Todos' },
  { word: '～さん', translation: 'Sr. | Sra. | Srta' },
  { word: '～ちゃん', translation: 'Sufijo para niña' },
  { word: '～くん', translation: 'Sufijo para niño' },
  { kanji: '～人', word: '～じん', translation: 'Sufijo para indicar nacionalidad' },
  { kanji: '先生', word: 'せんせい', translation: 'Profesor (tercera persona)' },
  { kanji: '教師', word: 'きょうし', translation: 'Profesor (primera persona)' },
  { kanji: '学生', word: 'がくせい', translation: 'Estudiante' },
  { kanji: '会社員', word: 'かいしゃいん', translation: 'Empleado de una empresa' },
  { kanji: '～社員', word: '～しゃいん', translation: 'Empleado de ～' },
  { kanji: '銀行員', word: 'ぎんこういん', translation: 'Banquero' },
  { kanji: '医者', word: 'いしゃ', translation: 'Medico' },
  { kanji: '研究者', word: 'けんきゅうしゃ', translation: 'Investigador' },
  { word: 'エンジニア', translation: 'Ingeniero' },
  { kanji: '大学', word: 'だいがく', translation: 'Universidad' },
  { kanji: '病院', word: 'びょういん', translation: 'Hospital' },
  { kanji: '電気', word: 'でんき', translation: 'Electricidad' },
  { kanji: '誰', word: 'だれ', translation: '¿Quién?' },
  { kanji: '何方', word: 'どなた', translation: '¿Quién? (formal).' },
  { kanji: '～歳', word: '～さい', translation: '～Años de edad.' },
  { kanji: '何歳', word: 'なんさい', translation: 'Cuántos años' },
  { kanji: '御いくつ', word: 'おいくつ', translation: 'Cuantos años (formal)' },
  { word: 'はい', translation: 'Si' },
  { word: 'いいえ', translation: 'No' },
  { kanji: '失礼ですが', word: 'しつれいですが', translation: 'Perdóname, pero...' },
  { kanji: 'お名前は', word: 'おなまえは', translation: '¿Cuál es tu nombre?', particles: { は: [4] } },
  { kanji: '初めまして', word: 'はじめまして', translation: 'Mucho gusto' },
  { word: 'どうぞ', translation: 'Encantado (de conocerlo)' },
  { word: 'よろしく', translation: 'Saludo' },
  { kanji: '此方は～さんです', word: 'こちらは～さんです', translation: 'Este es el Sr. / Sra. ～', particles: { は: [3] } },
  { kanji: '～から来ました', word: '～からきました', translation: 'Vengo desde ～' }
  // { kanji: '', word: '', translation: '' }
]
