import { Word } from './interfaces'

export const words: Word[] = [
  // Leccion 1
  { kanji: '漢字', word: 'かんじ', translation: 'Kanji' },
  { word: 'ひらがな', translation: 'Hiragana' },
  { word: 'カタカナ', translation: 'Katakana' },
  { word: 'はじめましょう', translation: 'Vamos a empezar.' },
  { word: 'おわりましょう', translation: 'Vamos a terminar.' },
  { word: 'やすみましょう', translation: 'Vamos a descansar.' },
  { kanji: '一度', word: 'いちど', translation: 'De nuevo' },
  { word: 'もう', translation: 'Ya.' },
  { kanji: '名前', word: 'なまえ', translation: 'Nombre .' },
  { kanji: '試験', word: 'しけん', translation: 'Examen .' },
  { kanji: '宿題', word: 'しゅくだい', translation: 'Tarea .' },
  { kanji: '質問', word: 'しつもん', translation: 'Pregunta .' },
  { word: 'こたえ', translation: 'Respuesta .' },
  { kanji: '例', word: 'れい', translation: 'Ejemplo.' },
  { word: 'わかりますか', translation: '¿Entiendes?' },
  { word: 'わかります', translation: 'Entiendo.' },
  { word: 'わかりません', translation: 'No entiendo.' },
  { word: 'けっこうです', translation: 'Está bien.' },
  { word: 'だめです', translation: 'Está mal.' },
  { word: 'おはようございます ', translation: 'Buenos Días.' },
  { word: 'こんにちは', translation: 'Hola.' },
  { word: 'こんばんは', translation: 'Buenas noches.' },
  { word: 'おやすみなさい', translation: 'Buenas noches' },
  { word: 'さようなら', translation: 'Chau.' },
  { word: 'ありがとうございます', translation: 'Muchas gracias.' },
  { word: 'すみません', translation: 'Disculpa, perdón.' },
  { word: 'おねがいします', translation: 'Por favor.' },
  { kanji: '零', word: 'れい', translation: '0.' },
  { word: 'ゼロ', translation: '0.' },
  { kanji: '一', word: 'いち', translation: '1.' },
  { kanji: '二', word: 'に', translation: '2.' },
  { kanji: '三', word: 'さん', translation: '3.' },
  { kanji: '午', word: 'ご', translation: '5.' },
  { kanji: '六', word: 'ろく', translation: '6.' },
  { kanji: '八', word: 'はち', translation: '8.' },
  { kanji: '九', word: 'きゅう', translation: '9.' },
  { kanji: '十', word: 'じゅう', translation: '10.' },
  { kanji: '私', word: 'わたし', translation: 'Yo.' },
  { kanji: '私達', word: 'わたしたち', translation: 'Nosotros.' },
  { kanji: 'あなた達', word: 'あなたたち', translation: 'Ustedes.' },
  { kanji: '彼達', word: 'かれたち', translation: 'Ellos.' },
  { kanji: '彼女達', word: 'かのじょたち', translation: 'Ellas.' },
  { kanji: '貴方', word: 'あなた', translation: 'Tu.' },
  { kanji: 'あの人', word: 'あのひと', translation: 'Aquella Persona .' },
  { kanji: 'あの方', word: 'あのかた', translation: 'Aquella Persona' },
  { kanji: '皆さん', word: 'みなさん', translation: 'Todos.' },
  { kanji: '先生', word: 'せんせい', translation: 'Maestro, profesor (en 2da persona).' },
  { kanji: '教師', word: 'きょうし', translation: 'Maestro, profesor (en 1era persona).' },
  { kanji: '学生', word: 'がくせい', translation: 'Estudiante.' },
  { kanji: '会社員', word: 'かいしゃいん', translation: 'Empleado de una empresa.' },
  { kanji: '銀行員', word: 'ぎんこういん', translation: 'Banquero.' },
  { kanji: '医者', word: 'いしゃ', translation: 'Medico.' },
  { kanji: '研究者', word: 'けんきゅうしゃ', translation: 'Investigador.' },
  { word: 'エンジニア', translation: 'Ingeniero.' },
  { kanji: '大学', word: 'だいがく', translation: 'Universidad.' },
  { kanji: '病院', word: 'びょういん', translation: 'Hospital.' },
  { kanji: '電気', word: 'でんき', translation: 'Electricidad.' },
  { kanji: '誰', word: 'だれ', translation: '¿Quién?.' },
  { kanji: '何方', word: 'どなた', translation: '¿Quién? (formal).' },
  { kanji: '何歳', word: 'なんさい', translation: 'Cuántos años .' },
  { word: 'おいくつ', translation: 'Cuantos años' },
  { word: 'はい', translation: 'Si.' },
  { word: 'いいえ', translation: 'No.' },
  { word: 'しつれいですが', translation: 'Perdóname, pero...' },
  { word: 'おなまえは？', translation: '¿Cómo se llama? /¿Cual es su nombre?' },
  { word: 'はじめまして', translation: 'Encantado de conocerte.' },
  { word: 'よろしくおねがいします', translation: 'Por favor, cuída de mí, Espero contar con tu ayuda.' },
  // Final de leccion 01
  { word: 'これ', translation: 'Esto. | Este. | Esta.' },
  { word: 'それ', translation: 'Eso. | Ese. | Esa.' },
  { word: 'あれ', translation: 'Aquel. | Aquello. | Aquella.' },
  { kanji: '本', word: 'ほん', translation: 'Libro.' },
  { kanji: '辞書', word: 'じしょ', translation: 'Diccionario .' },
  { kanji: '雑誌', word: 'ざっし', translation: 'Revista .' },
  { kanji: '新聞', word: 'しんぶん', translation: 'Periódico .' },
  { word: 'ノート', translation: 'Cuaderno .' },
  { kanji: '手帳', word: 'てちょう', translation: 'Agenda .' },
  { kanji: '名刺', word: 'めいし', translation: 'Tarjeta de presentación .' },
  { word: 'カード', translation: 'Tarjeta .' },
  { word: 'テレホンカード', translation: 'Tarjeta de teléfono .' },
  { kanji: '鉛筆', word: 'えんぴつ', translation: 'Lápiz.' },
  { word: 'ボールペン', translation: 'Bolígrafo .' },
  { word: 'シャープペンシル', translation: 'Lápiz mecánico .' },
  { kanji: '鍵', word: 'かぎ', translation: 'Llave .' },
  { kanji: '時計', word: 'とけい', translation: 'Reloj .' },
  { kanji: '傘', word: 'かさ', translation: 'Paragua / Sombrilla .' },
  { kanji: '鞄', word: 'かばん', translation: 'Bolso , maleta.' },
  { word: 'カセットテープ', translation: 'Cinta de casete .' },
  { word: 'テープレコーダー', translation: 'Grabadora de casete .' },
  { word: 'テレビ', translation: 'Televisión .' },
  { word: 'ラジオ', translation: 'Radio .' },
  { word: 'カメラ', translation: 'Cámara .' },
  { word: 'コンピューター', translation: 'Computadora.  漢字  ひらがな  カタカナ  Español' },
  { kanji: '自動車', word: 'じどうしゃ', translation: 'Automóvil .' },
  { kanji: '机', word: 'つくえ', translation: 'Escritorio .' },
  { kanji: '椅子', word: 'いす', translation: 'Silla.' },
  { word: 'チョコレート', translation: 'Chocolate .' },
  { word: 'コーヒー', translation: 'Café .' },
  { kanji: '英語', word: 'えいご', translation: 'El idioma i nglés .' },
  { kanji: '日本語', word: 'にほんご', translation: 'El idioma japonés.' },
  { kanji: '何', word: 'なん', translation: 'Qué.' },
  { word: 'そう', translation: 'Si, eso.' },
  { word: 'あのう', translation: 'Eh…, esto… (lit . “mmm”' },
  { word: 'えっ', translation: '¿Cómo? (se usa al' },
  { word: 'ほんのきもちです', translation: 'Es solo un pequeño' },
  { word: 'どうぞ', translation: 'Adelante .' },
  { word: 'どうも', translation: 'Gracias .' },
  { word: 'ありがとう', translation: '［ございます ］  Muchísimas gracias .' },
  { word: 'これから', translation: 'お世話に' },
  { word: 'これから', translation: 'おせわに' },
  { word: 'こちらこそ', translation: '［どうぞ］' },
  { word: 'よろしく', translation: '［お願いします］  こちらこそ' },
  { word: 'よろしく', translation: '［おねがいします］   Yo también estoy' },
  { word: 'よろしく', translation: '［おねがいします］ ). Vocabulario lección 03' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'ここ', translation: 'Aquí,  en este lugar .' },
  { word: 'そこ', translation: 'Ahí, en ese lugar .' },
  { word: 'あそこ', translation: 'Allí, en aquel lugar .' },
  { word: 'どこ', translation: '¿Donde? | ¿Qué' },
  { word: 'こちら', translation: 'Aquí, este lugar' },
  { word: 'そちら', translation: 'Ahí, ese lugar (formal) .' },
  { word: 'あちら', translation: 'Allí, aquel lugar' },
  { word: 'どちら', translation: '¿Dónde? | ¿Qué lugar?' },
  { kanji: '教室', word: 'きょうしつ', translation: 'Aula .' },
  { kanji: '食堂', word: 'しょくどう', translation: 'Comedor .' },
  { kanji: '事務所', word: 'じむしょ', translation: 'Oficina .' },
  { kanji: '会議室', word: 'かいぎしつ', translation: 'Sala de reuniones .' },
  { kanji: '受付', word: 'うけつけ', translation: 'Recepción .' },
  { word: 'ロビー', translation: 'Lobby .' },
  { kanji: '部屋', word: 'へや', translation: 'Habitación , cuarto.' },
  { word: 'おてあらい', translation: 'トイレ  Baño .' },
  { kanji: '階段', word: 'かいだん', translation: 'Escalera  (manual).' },
  { word: 'エレベーター', translation: 'Ascensor , elevador.' },
  { word: 'エスカレーター', translation: 'Escalera mecánica.' },
  { kanji: '煙草', word: 'たばこ', translation: 'Tabaco .' },
  { kanji: '場', word: 'うりば', translation: 'Sección .' },
  { kanji: '地下', word: 'ちか', translation: 'Subsuelo , sótano.' },
  { kanji: '何階', word: 'なんがい', translation: 'Que piso .' },
  { kanji: '会社', word: 'かいしゃ', translation: 'Trabajo .' },
  { kanji: '家', word: 'うち', translation: 'Casa (1era persona) .' },
  { kanji: '家', word: 'いえ', translation: 'Casa (2da persona).' },
  { kanji: '電話', word: 'でんわ', translation: 'Teléfono , llamada' },
  { kanji: '靴', word: 'くつ', translation: 'Zapato . 漢字  ひらがな  カタカナ  Español' },
  { word: 'ネクタイ', translation: 'Corbata.' },
  { word: 'ワイン', translation: 'Vino.' },
  { word: 'いくら', translation: 'Cuanto.' },
  { kanji: '百', word: 'ひゃく', translation: '100.' },
  { kanji: '千', word: 'せん', translation: '1.000.' },
  { kanji: '万', word: 'まん', translation: '10.000.' },
  { word: 'すみません', translation: 'Perdón (formula' },
  { word: 'じゃ', translation: 'Bueno, entonces.' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'おきます', translation: 'Despertarse .' },
  { word: 'ねます', translation: 'Acostarse, irse a la' },
  { word: 'はたらきます', translation: 'Trabajar .' },
  { word: 'やすみます', translation: 'Descansar , estar de' },
  { word: 'べんきょうします', translation: 'Estudiar .' },
  { word: 'おわります', translation: 'Terminar .' },
  { word: 'デパート', translation: 'Tienda departamental .' },
  { kanji: '銀行', word: 'ぎんこう', translation: 'Banco , institución' },
  { kanji: '郵便局', word: 'ゆうびんきょく', translation: 'Oficina de correo .' },
  { kanji: '図書館', word: 'としょかん', translation: 'Biblioteca .' },
  { kanji: '美術館', word: 'びじゅつかん', translation: 'Museo de arte .' },
  { kanji: '今', word: 'いま', translation: 'Ahora .' },
  { kanji: '何時', word: 'なんじ', translation: 'Qué hora .' },
  { kanji: '何分', word: 'なんぷん', translation: 'Qué minutos .' },
  { kanji: '午前', word: 'ごぜん', translation: 'a.m., de la m añana .' },
  { kanji: '午後', word: 'ごご', translation: 'p.m., de la t arde .' },
  { kanji: '朝', word: 'あさ', translation: 'La m añana .' },
  { kanji: '昼', word: 'ひる', translation: 'El medio dia, la tarde .' },
  { kanji: '一昨日', word: 'おととい', translation: 'Antes de ayer .' },
  { kanji: '昨日', word: 'きのう', translation: 'Ayer .' },
  { kanji: '今日', word: 'きょう', translation: 'Hoy.' },
  { kanji: '明日', word: 'あした', translation: 'Mañana .' },
  { kanji: '明後日', word: 'あさって', translation: 'Pasado mañana .' },
  { kanji: '今朝', word: 'けさ', translation: 'Esta mañana .' },
  { kanji: '今晩', word: 'こんばん', translation: 'Esta noche .' },
  { word: 'やすみ', translation: 'Descanso , dia libre, dia' },
  { word: 'ひるやすみ', translation: 'Hora del almuerzo,' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { kanji: '毎朝', word: 'まいあさ', translation: 'Todas las mañanas .' },
  { kanji: '毎晩', word: 'まいばん', translation: 'Todas las noches .' },
  { kanji: '毎日', word: 'まいにち', translation: 'Todos los días .' },
  { kanji: '月曜日', word: 'げつようび', translation: 'Lunes .' },
  { kanji: '火曜日', word: 'かようび', translation: 'Marte s.' },
  { kanji: '水曜日', word: 'すいようび', translation: 'Miercoles .' },
  { kanji: '木曜日', word: 'もくようび', translation: 'Jueves .' },
  { kanji: '金曜日', word: 'きんようび', translation: 'Viernes .' },
  { kanji: '土曜日', word: 'どようび', translation: 'Sábado .' },
  { kanji: '日曜日', word: 'にちようび', translation: 'Domingo .' },
  { kanji: '何曜日', word: 'なんようび', translation: 'Qué dia .' },
  { kanji: '番号', word: 'なんばん', translation: 'Qué número .' },
  { word: 'そちら', translation: 'Ese lugar .' },
  { word: 'たいへんですね', translation: '¡Qué duro! ¡Cuánto  lo' },
  { word: 'えーと', translation: 'Bueno, déjame ver .' },
  { word: 'おねがいします', translation: 'Por favor .' },
  { word: 'かしこまりました', translation: 'Ciertamente .' },
  { word: 'おといあわせの', translation: 'El número consultado .' },
  { word: 'ありがとう', translation: 'ごさいした   Muchas gracias . Vocabulario Lección  05' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'いきます', translation: 'Ir.' },
  { word: 'きます', translation: 'Venir .' },
  { word: 'かえります', translation: 'Volver , regresar, irse' },
  { kanji: '学校', word: 'がっこう', translation: 'Escuela .' },
  { word: 'スーパー', translation: 'Supermercado .' },
  { kanji: '駅', word: 'えき', translation: 'Estación .' },
  { kanji: '飛行機', word: 'ひこうき', translation: 'Avión .' },
  { kanji: '船', word: 'ふね', translation: 'Buque, b arco .' },
  { kanji: '電車', word: 'でんしゃ', translation: 'Tren  eléctrico .' },
  { kanji: '鉄', word: 'ちかてつ', translation: 'Subterráneo' },
  { kanji: '新幹線', word: 'しんかんせん', translation: 'Tren Bala .' },
  { word: 'バス', translation: 'Autobús (Micro) .' },
  { word: 'タクシー', translation: 'Taxi.' },
  { kanji: '車', word: 'じてんしゃ', translation: 'Bicicleta .' },
  { word: 'あるいて', translation: 'A pie , cam inando.' },
  { kanji: '人', word: 'ひと', translation: 'Persona , gente.' },
  { kanji: '友達', word: 'ともだち', translation: 'Amigo (s).' },
  { kanji: '彼', word: 'かれ', translation: 'El, novio.' },
  { kanji: '彼女', word: 'かのじょ', translation: 'Ella, novi a.' },
  { kanji: '家族', word: 'かぞく', translation: 'Familia .' },
  { word: 'ひとりで', translation: 'Solitario .' },
  { kanji: '先週', word: 'せんしゅう', translation: 'La semana pasada .' },
  { kanji: '今週', word: 'こんしゅう', translation: 'Esta semana .' },
  { kanji: '来週', word: 'らいしゅう', translation: ', la p róxima semana .' },
  { kanji: '先月', word: 'せんげつ', translation: 'El mes pasado .' },
  { kanji: '今月', word: 'こんげつ', translation: 'Este mes , el mes' },
  { kanji: '来月', word: 'らいげつ', translation: 'El próximo mes .' },
  { kanji: '去年', word: 'きょうねん', translation: 'El año pasado .' },
  { kanji: '今年', word: 'ことし', translation: 'Este año , el año' },
  { kanji: '来年', word: 'らいねん', translation: 'El año que viene, el' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { kanji: '何月', word: 'なんがつ', translation: 'Qué mes .' },
  { kanji: '一日', word: 'ついたち', translation: 'Dia 1 del mes .' },
  { kanji: '二日', word: 'ふつか', translation: 'Dia 2 del mes .' },
  { kanji: '三日', word: 'みっか', translation: 'Dia 3 del mes .' },
  { kanji: '四日', word: 'よっか', translation: 'Dia 4 del mes .' },
  { kanji: '五日', word: 'いつか', translation: 'Dia 5 del mes .' },
  { kanji: '六日', word: 'むいか', translation: 'Dia 6 del mes .' },
  { kanji: '七日', word: 'なのか', translation: 'Dia 7 del mes .' },
  { kanji: '八日', word: 'ようか', translation: 'Dia 8 del mes .' },
  { kanji: '九日', word: 'ここのか', translation: 'Dia 9 del mes .' },
  { kanji: '十日', word: 'とおか', translation: 'Dia 10 del mes .' },
  { kanji: '十四日', word: 'じゅうよっか', translation: 'Dia 14 del mes .' },
  { kanji: '二十日', word: 'はつか', translation: 'Dia 20 del mes .' },
  { kanji: '二十四日', word: 'にじゅうよっか', translation: 'Dia 24 del mes .' },
  { kanji: '何日', word: 'なんにち', translation: 'Qué dia .' },
  { word: 'いつ', translation: '¿Cuándo? .' },
  { kanji: '誕生日', word: 'たんじょうび', translation: 'Cumpleaños .' },
  { kanji: '普通', word: 'ふつう', translation: 'Tren local .' },
  { kanji: '急行', word: 'きゅうこう', translation: 'Tren rápido .' },
  { kanji: '特急', word: 'とっきゅう', translation: 'Tren exprés .' },
  { word: 'つぎの', translation: 'Siguiente .' },
  { word: 'どういたしまして', translation: 'De nada .' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'きります', translation: 'Cortar' },
  { word: 'おくります', translation: 'Enviar' },
  { word: 'あげます', translation: 'Dar' },
  { word: 'もらいます', translation: 'Recibir' },
  { word: 'かします', translation: 'Prestar' },
  { word: 'かります', translation: 'Pedir prestado' },
  { word: 'おしえます', translation: 'Enseñar' },
  { word: 'ならいます', translation: 'Aprender' },
  { kanji: '手', word: 'て', translation: 'Mano' },
  { word: 'はし', translation: 'Palillos chinos' },
  { word: 'スプーン', translation: 'Cuchara' },
  { word: 'ナイフ', translation: 'Cuchillo' },
  { word: 'フォーク', translation: 'Tenedor' },
  { word: 'はさみ', translation: 'Tijeras' },
  { word: 'ファクス', translation: 'Fax' },
  { word: 'ワープロ', translation: 'Procesador de texto' },
  { word: 'パソコン', translation: 'Comp utador a personal' },
  { word: 'パンチ', translation: 'Golpe / Puñetazo' },
  { word: 'ホッチキス', translation: 'Engrapadora' },
  { word: 'セロテープ', translation: 'Cinta s cotch' },
  { word: 'けし', translation: 'ゴマ  Goma de borrar' },
  { kanji: '紙', word: 'かみ', translation: 'Papel' },
  { kanji: '花', word: 'はな', translation: 'Flor' },
  { word: 'シャツ', translation: 'Camisa' },
  { word: 'プレゼント', translation: 'Presente, regalo' },
  { kanji: '荷物', word: 'にもつ', translation: 'Equipaje, paquete' },
  { kanji: '金', word: 'おかね', translation: 'Dinero' },
  { kanji: '切符', word: 'きっぷ', translation: 'Ticket, boleto' },
  { word: 'クリスマス', translation: 'Navidad' },
  { kanji: '父', word: 'ちち', translation: '(Mi) Papá' },
  { kanji: '母', word: 'はは', translation: '(Mi)  Mamá' },
  { word: 'おとうさん', translation: 'Padre (de alguien)' },
  { word: 'おかあさん', translation: 'Madre (de alguien)' },
  { word: 'もう', translation: 'Ya' },
  { word: 'まだ', translation: 'Todavía  no Vocabulario Lección  7' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'これから', translation: 'Desde ahora' },
  { word: 'ね', translation: '¡Qué  bonito  [~]!' },
  { word: 'ごめん', translation: 'ください   Disculpe. ¿Hay' },
  { word: 'いらっしゃい', translation: 'Qué bien que hayas' },
  { word: 'どうぞ', translation: 'おあがり' },
  { word: 'ください', translation: 'Pase  / Adelante  por' },
  { word: 'りょこう', translation: 'Viaje' },
  { word: 'おみやげ', translation: 'Souv enir' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'おおきい', translation: 'Grande / Largo' },
  { word: 'ちいさい', translation: 'Pequeño' },
  { word: 'あたらしい', translation: 'Nuevo' },
  { word: 'ふるい', translation: 'Viejo' },
  { word: 'わるい', translation: 'Malo' },
  { word: 'あつい', translation: 'Caliente' },
  { word: 'さむい', translation: 'frío (en referencia a' },
  { word: 'つめたい', translation: 'frío (refiriéndose al' },
  { word: 'むずかしい', translation: 'Difícil' },
  { word: 'やさしい', translation: 'Fácil / Amable' },
  { word: 'たかい', translation: 'Alto / Caro.' },
  { word: 'やすい', translation: 'Barato' },
  { word: 'ひくい', translation: 'Bajo' },
  { word: 'おもしろい', translation: 'Interesante' },
  { word: 'おいしい', translation: 'Delicioso' },
  { word: 'いそがしい', translation: 'Ocupado' },
  { word: 'たのしい', translation: 'Divertido' },
  { word: 'しろい', translation: 'Blanco' },
  { word: 'くろい', translation: 'Negro' },
  { word: 'あかい', translation: 'Rojo  漢字  ひらがな  かたかな  Español' },
  { word: 'あおい', translation: 'Azul' },
  { kanji: '桜', word: 'さくら', translation: 'Flores de cerezo' },
  { kanji: '山', word: 'やま', translation: 'Montaña' },
  { kanji: '町', word: 'まち', translation: 'Ciudad' },
  { kanji: '物', word: 'たべもの', translation: 'Comida' },
  { kanji: '車', word: 'くるま', translation: 'Carro / Auto' },
  { kanji: '所', word: 'ところ', translation: 'Lugar' },
  { kanji: '寮', word: 'りょう', translation: 'Dormitorio' },
  { kanji: '勉強', word: 'べんきょう', translation: 'Estudio' },
  { kanji: '生活', word: 'せいかつ', translation: 'Vida (diaria)' },
  { kanji: '仕事', word: 'しごと', translation: 'Trabajo' },
  { word: 'どう', translation: 'cómo' },
  { word: 'どんな', translation: 'Qué tipo / Qué cosa' },
  { word: 'どれ', translation: 'cuál ( entre  tres o' },
  { word: 'とても', translation: 'Mucho' },
  { word: 'あまり', translation: 'Muy poco (se usa en' },
  { word: 'そして', translation: 'Entonces, y (se utiliza' },
  { word: 'おげんきですか', translation: '¿Cómo estás?' },
  { word: 'そうですね', translation: '¡Oh, si!' },
  { kanji: '生活', word: 'にほんのせいかつ', translation: 'Vida en Japón' },
  { word: 'もう', translation: '一杯ぱい' },
  { word: 'いかが', translation: 'ですか  ［～、 ］' },
  { word: 'もう', translation: 'いっぱ' },
  { word: 'いかが', translation: 'ですか   ¿No quieres otra taza' },
  { word: 'いいえ', translation: 'けっこうです   No, gracias' },
  { word: 'そろそろ', translation: '失礼します。  そろそろ' },
  { word: 'また', translation: 'いらっしゃてください   Por favor vuelvan' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'わかります', translation: '［が］  Entiendo' },
  { word: 'あります', translation: '［が］  Haber' },
  { word: 'じょうず', translation: '［な］   Bueno en' },
  { kanji: '料理', word: 'りょうり', translation: 'Comida, cocina' },
  { kanji: '物', word: 'のみもの', translation: 'Bebidas' },
  { word: 'スポーツ', translation: 'Deportes' },
  { kanji: '柳生', word: 'やぎゅう', translation: 'Baseball' },
  { word: 'ダンス', translation: 'Baile' },
  { kanji: '音楽', word: 'おんがく', translation: 'Música' },
  { kanji: '歌', word: 'うた', translation: 'Canción' },
  { word: 'クラシック', translation: 'Clásica' },
  { word: 'ジャズ', translation: 'Jazz' },
  { word: 'コンサート', translation: 'Concierto' },
  { word: 'カラオケ', translation: 'Karaoke' },
  { kanji: '歌舞伎', word: 'かぶき', translation: 'Teatro tradicional' },
  { kanji: '絵', word: 'え', translation: 'Imagen, dibujar' },
  { kanji: '字', word: 'じ', translation: 'Letra, carácter' },
  { kanji: '漢字', word: 'かんじ', translation: 'Kanji' },
  { word: 'ひらがな', translation: 'Hiragana' },
  { word: 'カタカナ', translation: 'Katakana' },
  { kanji: '字', word: 'ローマじ', translation: 'Romaji' },
  { kanji: '金', word: 'こまかいおかね', translation: 'Cambio pequeño' },
  { word: 'チケット', translation: 'Ticket' },
  { kanji: '時間', word: 'じかん', translation: 'Tiempo' },
  { kanji: '用事', word: 'ようじ', translation: 'Algo que hacer,' },
  { kanji: '約束', word: 'やくそく', translation: 'Promesa, cita' },
  { kanji: '主人', word: 'ごしゅじん', translation: 'Esposo (de alguien)  漢字  ひらがな  カタカナ  Español' },
  { kanji: '主人', word: 'おっと', translation: '/しゅじん   Esposo (mío)' },
  { word: 'おくさん', translation: 'Esposa (de alguien)' },
  { kanji: '家内', word: 'つま', translation: '/かない   Esposa (mía)' },
  { kanji: '子供', word: 'こども', translation: 'Niño' },
  { word: 'よく', translation: 'A menudo' },
  { word: 'だいたい', translation: 'La mayoría' },
  { word: 'たくさん', translation: 'Mucho' },
  { word: 'すこし', translation: 'Un poco' },
  { kanji: '全然', word: 'ぜんぜん', translation: 'Nada' },
  { word: 'はやく', translation: 'Rápido' },
  { word: 'どうして', translation: '¿Por qué?' },
  { word: 'ざんねんです', translation: '［ね］  Que lastima, estoy' },
  { word: 'すみません', translation: 'Perdón' },
  { word: 'もしもし', translation: 'Hola (usado solo en' },
  { word: 'ああ', translation: 'Oh' },
  { word: 'いっしょに', translation: 'いかがですか。   ¿Te gustaría unirte' },
  { word: 'だめですか', translation: '¿Así que no puedes?' },
  { word: 'またこんど', translation: 'La próxima vez' },
  { kanji: '生活', word: 'おねがいします', translation: 'Por favor' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'あります', translation: '［が］  Haber  (cosas' },
  { kanji: '人', word: 'おとこのひと', translation: 'Hombre' },
  { kanji: '人', word: 'おんなのひと', translation: 'Mujer' },
  { kanji: '子', word: 'おとこのこ', translation: 'Niño' },
  { kanji: '子', word: 'おんなの', translation: 'こ  Niña' },
  { kanji: '犬', word: 'いぬ', translation: 'Perro' },
  { kanji: '猫', word: 'ねこ', translation: 'Gato' },
  { kanji: '木', word: 'き', translation: 'Árbol' },
  { kanji: '物', word: 'もの', translation: 'Cosa' },
  { word: 'フィルム', translation: 'Película' },
  { kanji: '電池', word: 'でんち', translation: 'Batería' },
  { kanji: '箱', word: 'はこ', translation: 'Caja' },
  { word: 'スイッチ', translation: 'Switch' },
  { kanji: '冷蔵庫', word: 'れいぞうこ', translation: 'Refri gerador' },
  { word: 'テーブル', translation: 'Mes a' },
  { word: 'ベッド', translation: 'Cama' },
  { kanji: '棚', word: 'たな', translation: 'Estante' },
  { word: 'ドア', translation: 'Puerta' },
  { kanji: '窓', word: 'まど', translation: 'Ventana' },
  { word: 'ポスト', translation: 'Buzón  de correo' },
  { word: 'ビル', translation: 'Edificio' },
  { kanji: '公園', word: 'こうえん', translation: 'Parque' },
  { kanji: '喫茶店', word: 'きっさて', translation: 'ん コーヒー ショップ  Cafetería' },
  { kanji: '本屋', word: 'ほんや', translation: 'Librería' },
  { kanji: '場', word: 'のりば', translation: 'Para de t axi, tren,' },
  { kanji: '県', word: 'けん', translation: 'Prefectura' },
  { kanji: '上', word: 'うえ', translation: 'Arriba' },
  { kanji: '下', word: 'した', translation: 'Abajo' },
  { kanji: '前', word: 'まえ', translation: 'Al frente' },
  { word: 'うしろ', translation: 'Atrás , detrás 漢字  ひらがな  カタカナ  Español' },
  { kanji: '右', word: 'みぎ', translation: 'Derecha' },
  { kanji: '左', word: 'ひだり', translation: 'Izquierda' },
  { kanji: '中', word: 'なか', translation: 'Adentro' },
  { kanji: '外', word: 'そと', translation: 'Afuera' },
  { kanji: '隣', word: 'となり', translation: 'Siguiente' },
  { word: 'ちかく', translation: 'Cerca' },
  { kanji: '間', word: 'あいだ', translation: 'Entre' },
  { word: 'いちばん', translation: '～  El favorito.' },
  { word: 'うえ', translation: ')  Arriba de todo' },
  { kanji: '棚', word: 'たな', translation: 'Estante  completo' },
  { word: 'すみません', translation: '。  Muchas gracias' },
  { word: 'チリソー', translation: 'ス Salsa de Chile' },
  { kanji: '奥', word: 'おく', translation: 'El final, o al final' },
  { word: 'スパイスコーナ', translation: 'ー Sección  de Picantes' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'います', translation: 'Estar (en Japón )' },
  { word: 'かかりま', translation: 'す  Tomar' },
  { word: 'やすみます', translation: 'Tomarse un dia' },
  { word: 'ひとつ', translation: 'Una cosa' },
  { word: 'ふたつ', translation: 'Dos cosas' },
  { word: 'みっつ', translation: 'Tres cosas' },
  { word: 'よっつ', translation: 'Cuatro cosas' },
  { word: 'いつつ', translation: 'Cinco cosas' },
  { word: 'むっつ', translation: 'Seis cosas' },
  { word: 'ななつ', translation: 'Siete cosas' },
  { word: 'やっつ', translation: 'Ocho cosas' },
  { word: 'ここのつ', translation: 'Nueve  cosas' },
  { kanji: '十', word: 'とお', translation: 'Diez cosas' },
  { word: 'いくつ', translation: '¿Cuántas  cosas ?' },
  { kanji: '一人', word: 'ひとり', translation: 'Una persona' },
  { kanji: '二人', word: 'ふたり', translation: 'Dos personas' },
  { word: 'りんご', translation: 'Manzana' },
  { word: 'みかん', translation: 'Mandarina' },
  { word: 'サンドイッ', translation: 'チ Sándwich' },
  { word: 'カレー', translation: '［ライス ］ Curry de arroz' },
  { word: 'アイスクリー', translation: 'ム Helado' },
  { kanji: '切手', word: 'きって', translation: 'Estampillas  漢字  ひらがな  カタカナ  Español' },
  { kanji: '葉書', word: 'はがき', translation: 'Plantilla de' },
  { kanji: '封筒', word: 'ふうとう', translation: 'Sobre' },
  { kanji: '速達', word: 'そくたつ', translation: 'Entrega especial' },
  { kanji: '書留', word: 'かきとめ', translation: 'Correo' },
  { kanji: '航空便', word: 'こうくう', translation: 'びん エアメー ル Correo aéreo' },
  { kanji: '船便', word: 'ふなびん', translation: 'Correo  marino' },
  { kanji: '両親', word: 'りょうしん', translation: 'Padres' },
  { kanji: '兄弟', word: 'きょうだ', translation: 'い  Hermanos' },
  { kanji: '兄', word: 'あに', translation: 'Mi hermano' },
  { word: 'おにいさん', translation: 'El hermano' },
  { kanji: '姉', word: 'あね', translation: 'Mi hermana' },
  { word: 'おねえさ', translation: 'ん  La hermana' },
  { kanji: '弟', word: 'おとうと', translation: 'Mi hermano' },
  { word: 'おとうとさん', translation: 'El hermano' },
  { kanji: '妹', word: 'いもうと', translation: 'Mi hermana' },
  { word: 'いもうとさ', translation: 'ん  La hermana' },
  { kanji: '外国', word: 'がいこく', translation: 'País extran jero' },
  { word: 'ん', translation: '～semanas' },
  { word: 'チリソー', translation: 'ス ～aproximado' },
  { word: 'い', translation: '～cuánto  dura' },
  { word: 'ぜんぶで', translation: 'En total' },
  { kanji: '皆', word: 'みんな', translation: 'Todos' },
  { word: 'いらしゃいませ', translation: 'Bienvenido /' },
  { word: 'おでかけです', translation: 'か  ¿Vas a salir?' },
  { word: 'ゃい', translation: 'いっていらっしゃ い  Hasta la vista.' },
  { word: 'いっていきます', translation: 'Me voy - hasta' },
  { word: 'それから', translation: 'y, además' },
  { word: 'オーストラリ', translation: 'ア Australia' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'かんたん', translation: '［な］  Fácil' },
  { word: 'ちかい', translation: 'Cerca' },
  { word: 'とおい', translation: 'Lejos' },
  { word: 'はやい', translation: 'Rápido ,' },
  { word: 'おそい', translation: 'Lento, tarde' },
  { word: 'あたたか', translation: 'い  Calien te' },
  { word: 'すずしい', translation: 'Frio' },
  { word: 'あまい', translation: 'Dulce' },
  { word: 'からい', translation: 'Picante' },
  { word: 'おもい', translation: 'Pesado' },
  { word: 'かるい', translation: 'Liviano' },
  { kanji: '季節', word: 'きせつ', translation: 'Estaciones' },
  { kanji: '春', word: 'はる', translation: 'Primavera' },
  { kanji: '夏', word: 'なつ', translation: 'Verano' },
  { kanji: '秋', word: 'あき', translation: 'Otoño' },
  { kanji: '冬', word: 'ふゆ', translation: 'Invierno' },
  { kanji: '天気', word: 'てんき', translation: 'Clima' },
  { kanji: '雨', word: 'あめ', translation: 'Lluvia' },
  { kanji: '雪', word: 'ゆき', translation: 'Nieve' },
  { word: 'くもり', translation: 'Nublado' },
  { word: 'ホテル', translation: 'Hotel' },
  { kanji: '空港', word: 'くうこう', translation: 'Aeropuerto' },
  { kanji: '海', word: 'うみ', translation: 'Mar, océano' },
  { kanji: '世界', word: 'せかい', translation: 'Mundo' },
  { word: 'パーティ', translation: 'ー Fiesta' },
  { kanji: '試験', word: 'しけん', translation: 'Examen' },
  { word: 'すきやき', translation: 'Sukiyaki  漢字  ひらがな  カタカナ  Español' },
  { kanji: '刺身', word: 'さしみ', translation: 'Sashimi' },
  { word: 'てんぷら', translation: 'Tempura' },
  { kanji: '花', word: 'いけばな', translation: 'Arreglo floral' },
  { kanji: '紅葉', word: 'もみじ', translation: 'Maple' },
  { word: 'どちら', translation: '¿Cuál? (entre' },
  { word: 'どちらも', translation: 'Ambas' },
  { word: 'ずっと', translation: 'Con diferencia ,' },
  { word: 'はじめて', translation: 'Por primera vez' },
  { word: 'おかえりなさ', translation: 'い  Bienvenido a' },
  { word: 'すごいですね', translation: '。  Es increíble ,' },
  { word: 'でも', translation: '¿Pero?' },
  { word: 'つかれました', translation: 'Estoy cansado.' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'あそびます', translation: 'Disfrutar, jugar' },
  { word: 'およぎます', translation: 'Nadar' },
  { word: 'むかえま', translation: 'す  Ir a la reunión ,' },
  { word: 'つかれます', translation: 'Estoy cansado' },
  { word: 'だします', translation: '［てがみを～］   Enviar [una' },
  { word: 'はいります', translation: '［きっさてんに～ ］  Entrar [a una' },
  { word: 'でます', translation: '［きっさてんを～］   Salir [de una' },
  { word: 'けっこんします', translation: 'Casarse,' },
  { word: 'かいものします', translation: 'Hacer shopping' },
  { word: 'しょくじしま', translation: 'す  comer, cenar' },
  { word: 'さんぽします', translation: '［こうえんを～ ］  Dar un paseo' },
  { word: 'ほしい', translation: 'Desear' },
  { word: 'さびしい', translation: 'Solitario' },
  { word: 'ひろい', translation: 'Amplio,' },
  { word: 'せまい', translation: 'Estrecho,' },
  { kanji: '市役所', word: 'しやくし', translation: 'ょ  Oficina' },
  { word: 'プール', translation: 'Piscina' },
  { kanji: '川', word: 'かわ', translation: 'Rio' },
  { kanji: '経済', word: 'けいざい', translation: 'Economía' },
  { kanji: '美術', word: 'びじゅつ', translation: 'Bellas artes' },
  { word: 'つり', translation: 'Pesca' },
  { word: 'スキー', translation: 'Esquí  漢字  ひらがな  カタカナ  Español' },
  { kanji: '空港', word: 'くうこう', translation: 'Aeropuerto' },
  { kanji: '会議', word: 'かいぎ', translation: 'Reunión,' },
  { kanji: '登録', word: 'とうろく', translation: 'Inscripción' },
  { kanji: '週末', word: 'しゅうま', translation: 'つ  Fin de semana' },
  { word: 'なにか', translation: 'Algo' },
  { word: 'どこか', translation: 'En alguna parte,' },
  { word: 'おなかがすきました', translation: '(Tengo) hambre' },
  { word: 'す', translation: 'おなかがいっぱいです   (Estoy) lleno' },
  { word: 'のどがかわきました', translation: '(Tengo) sed' },
  { word: 'そうですね', translation: 'Estoy de' },
  { word: 'そうしましょう', translation: 'Hagámoslo. (se' },
  { word: 'ごちゅうもんは', translation: '？  ¿Puedo tomar' },
  { kanji: '定食', word: 'ていしょく', translation: 'Comida' },
  { word: 'ぎゅうど', translation: 'ん  Gyudon' },
  { word: 'おまちください', translation: 'Por favor,' },
  { word: 'べつべつに', translation: 'Por separado' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'つけます', translation: 'Encender' },
  { word: 'けします', translation: 'Apagar' },
  { word: 'あけます', translation: 'Abrir' },
  { word: 'しめます', translation: 'Cerrar' },
  { word: 'いそぎます', translation: 'Apresurarse' },
  { word: 'まちます', translation: 'Esperar' },
  { word: 'とめます', translation: 'Detenerse,' },
  { word: 'まがりま', translation: 'す  Girar' },
  { word: 'もちます', translation: 'Mantener' },
  { word: 'とります', translation: 'Tomar' },
  { word: 'てつだいます', translation: 'Ayudar (con una' },
  { word: 'よびます', translation: 'Llamar' },
  { word: 'ほしい', translation: 'Desear' },
  { word: 'はなしま', translation: 'す  Hablar,' },
  { word: 'みせます', translation: 'Mostrar' },
  { word: 'おしえま', translation: 'す  Decir (una' },
  { word: 'はじめます', translation: 'Empezar, iniciar' },
  { word: 'コピーします', translation: 'Copiar' },
  { word: 'エアコン', translation: 'Aire' },
  { word: 'パスポート', translation: 'Pasaporte' },
  { kanji: '名前', word: 'なまえ', translation: 'Nombre' },
  { kanji: '住所', word: 'じゅうし', translation: 'ょ  Dirección' },
  { kanji: '地図', word: 'ちず', translation: 'Mapa' },
  { kanji: '塩', word: 'しお', translation: 'Sal' },
  { kanji: '砂糖', word: 'さとう', translation: 'Azúcar' },
  { kanji: '方', word: 'よみかた', translation: 'Cómo leer,' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'ゆっくり', translation: 'Despacio, sin' },
  { word: 'すぐ', translation: 'Inmediatamente' },
  { word: 'また', translation: 'De nuevo' },
  { word: 'あとで', translation: 'Después' },
  { word: 'もうすこし', translation: 'Un poquito mas' },
  { word: 'いいですよ', translation: '。  Claro ,' },
  { word: 'さあ', translation: 'Correcto (se' },
  { word: 'しんごうをみぎ', translation: 'へ' },
  { word: 'まっすぐいきます', translation: 'Recto' },
  { word: 'これでおねがいしま', translation: 'す。  Voy a pagar con' },
  { word: 'おつり', translation: 'Cambio' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'たちます', translation: 'Pararse' },
  { word: 'すわります', translation: 'Sentarse' },
  { word: 'つかいます', translation: 'Usar' },
  { word: 'おきます', translation: 'Poner' },
  { word: 'つくります', translation: 'Hacer , Prod ucir' },
  { word: 'うります', translation: 'Vender' },
  { word: 'しります', translation: 'Conocer' },
  { word: 'みます', translation: 'Ir a vivir' },
  { word: 'けんきゅうします', translation: 'Investigar' },
  { word: 'しる', translation: 'Saber' },
  { word: 'しっています', translation: 'Saber / c onocer' },
  { word: 'しりません', translation: 'No saber / no' },
  { word: 'すむ', translation: 'Vivir' },
  { word: 'すんでいます', translation: 'Vivir en ～' },
  { word: 'けんきゅうします', translation: 'Investigación' },
  { word: 'カタログ', translation: 'Catalogo' },
  { kanji: '時刻表', word: 'じこくひょう', translation: 'Horario' },
  { kanji: '服', word: 'ふく', translation: 'Ropa' },
  { kanji: '製品', word: 'せいひん', translation: 'Producto' },
  { word: 'ソフト', translation: 'Software' },
  { kanji: '専門', word: 'せんもん', translation: 'Especialidad,' },
  { kanji: '歯医者', word: 'はいしゃ', translation: 'Denti sta' },
  { kanji: '床屋', word: 'とこや', translation: 'Barbero' },
  { word: 'プレイガイド', translation: 'Agencia de' },
  { kanji: '独身', word: 'どくしん', translation: 'Soltero' },
  { word: 'とくに', translation: 'Especialmente' },
  { word: 'おもいだします', translation: 'Recordar ,' },
  { kanji: '家族', word: 'ごかぞく', translation: 'La familia de' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'いらっしゃいます', translation: 'います  de' },
  { kanji: '高校', word: 'こうこう', translation: 'Escuela' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'のります', translation: '［でんしゃに～］   Montar, subir (a' },
  { word: 'おります', translation: '［でんしゃを～］   Bajarse (de un' },
  { word: 'のりかえます', translation: 'Cambiar' },
  { word: 'あびます', translation: '［シャワー を～］   Tomar (ducha)' },
  { word: 'いれます', translation: 'Poner, insertar' },
  { word: 'だします', translation: 'Sacar, expulsar' },
  { word: 'はいります', translation: '［だいがくに～］   Entrar (a la' },
  { word: 'でます', translation: '［だいがくを～］   Graduarte (de la' },
  { word: 'やめます', translation: '［かいしゃを～］   Renunciar o' },
  { word: 'おします', translation: 'Presionar,' },
  { word: 'わかい', translation: 'Joven' },
  { word: 'ながい', translation: 'Largo' },
  { word: 'みじかい', translation: 'Corto' },
  { word: 'あかるい', translation: 'Brillante,' },
  { word: 'くらい', translation: 'Oscuro' },
  { word: 'せがたかい', translation: 'Alto' },
  { word: 'あたまがいい', translation: 'Listo, Inteligente' },
  { kanji: '体', word: 'からだ', translation: 'Cuerpo' },
  { kanji: '頭', word: 'あたま', translation: 'Cabeza' },
  { kanji: '髪', word: 'かみ', translation: 'Cabello' },
  { kanji: '顔', word: 'かお', translation: 'Cara' },
  { kanji: '目', word: 'め', translation: 'Ojos' },
  { kanji: '耳', word: 'みみ', translation: 'Oido, oreja' },
  { kanji: '口', word: 'くち', translation: 'Boca  漢字  ひらがな  かアカナ  Espa ñol' },
  { kanji: '歯', word: 'は', translation: 'Diente' },
  { kanji: '腹', word: 'おなか', translation: 'Estomago' },
  { kanji: '足', word: 'あし', translation: 'Pierna, pie' },
  { word: 'サービス', translation: 'Servicio' },
  { word: 'ジョギング', translation: 'Jogging' },
  { word: 'シャワー', translation: 'Ducha' },
  { kanji: '緑', word: 'みどり', translation: 'Verde' },
  { kanji: '神社', word: 'じんじゃ', translation: 'Santuario' },
  { kanji: '留学生', word: 'りゅうがくせい', translation: 'Estudiante' },
  { word: 'どうやって', translation: 'De qué manera,' },
  { word: 'まだまだです', translation: '(No,) Todavía' },
  { word: 'まず', translation: 'En primer lugar' },
  { word: 'キャッシュカー', translation: 'ド Tarjeta de' },
  { kanji: '暗証番号', word: 'あんしょうばんごう', translation: 'Número de' },
  { word: 'つぎに', translation: 'Siguiente, como' },
  { kanji: '金額', word: 'きんがく', translation: 'Cantidad de' },
  { kanji: '確認', word: 'かくにん', translation: 'Confirmación' },
  { word: 'かくにん', translation: '［をします ］  Confirmar' },
  { word: 'ボタン', translation: 'Botón' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'おぼえます', translation: 'Memorizar' },
  { word: 'わすれます', translation: 'Olvidar' },
  { word: 'なくします', translation: 'Perder' },
  { word: 'だします', translation: 'Entregar' },
  { word: 'はらいます', translation: 'Pagar' },
  { word: 'かえします', translation: 'Devolver' },
  { word: 'でかけます', translation: 'Salir' },
  { word: 'ぬぎます', translation: 'Quitarse (ropa,' },
  { word: 'もっていきます', translation: 'Agarrar,' },
  { word: 'もってきます', translation: 'Traer' },
  { word: 'しんぱいします', translation: 'Preocuparse' },
  { word: 'ざんぎょうします', translation: 'Trabajar h oras' },
  { word: 'しゅっちょうします', translation: 'Ir de viaje de' },
  { word: 'のみます', translation: 'Tomar [medicina]' },
  { word: 'はいります', translation: 'Tomar  [baño]' },
  { word: 'あぶない', translation: 'Peligroso' },
  { kanji: '問題', word: 'もんだい', translation: 'Pregunta,' },
  { word: 'こたえ', translation: 'Respuesta' },
  { kanji: '禁煙', word: 'きんえん', translation: 'No fumar' },
  { word: 'ほけんしょう', translation: 'Tarjeta de seguro' },
  { kanji: '風邪', word: 'かぜ', translation: 'Aire, frio' },
  { kanji: '病気', word: 'びょうき', translation: 'Enfermedad,' },
  { kanji: '漢字', word: 'ひらがな', translation: 'かアカナ  Espa ñol' },
  { kanji: '熱', word: 'ねつ', translation: 'Fiebre' },
  { kanji: '薬', word: 'くすり', translation: 'Medicina' },
  { kanji: '上着', word: 'うわぎ', translation: 'Chaqueta' },
  { kanji: '下着', word: 'したぎ', translation: 'Ropa interior' },
  { kanji: '先生', word: 'せんせい', translation: 'Doctor (utilizado' },
  { kanji: '神社', word: 'ですから', translation: 'Por lo tanto' },
  { kanji: '喉', word: 'のど', translation: 'Garganta' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'のぼります', translation: 'Escalar /Subir' },
  { word: 'とまります', translation: 'Estar' },
  { word: 'そうじします', translation: 'Limpiar' },
  { word: 'せんたくします', translation: 'Lavar  (ropa)' },
  { word: 'れんしゅうします', translation: 'Practicar' },
  { word: 'なります', translation: 'なります   Converti rse/volverse' },
  { word: 'ねむい', translation: 'Adormecido,' },
  { word: 'つよい', translation: 'Fuerte' },
  { word: 'よわい', translation: 'Debil' },
  { word: 'ちょうしがいい', translation: 'Estar en buenas' },
  { word: 'ちょうしがわるい', translation: 'Estar en malas' },
  { kanji: '調子', word: 'ちょうし', translation: 'Condicion' },
  { word: 'ゴルフ', translation: 'Golf' },
  { kanji: '相撲', word: 'すもう', translation: 'Lucha de Sumo' },
  { word: 'パチンコ', translation: 'Pinball' },
  { kanji: '茶', word: 'おちゃ', translation: 'Ceremoni a del te' },
  { kanji: '日', word: 'ひ', translation: 'Dia, fecha' },
  { kanji: '一度', word: 'いちど', translation: '1 vez' },
  { word: 'いちども', translation: 'Ninguna vez, nunca' },
  { kanji: '段々', word: 'だんだん', translation: 'Gradua lmente' },
  { word: 'もうすぐ', translation: 'Pronto' },
  { word: 'おかげさまで', translation: 'Gracias  (se usa' },
  { kanji: '乾杯', word: 'かんぱい', translation: 'Salud' },
  { word: 'じつは', translation: 'De hecho , a decir' },
  { word: 'ダイエット', translation: 'Dieta' },
  { word: 'なんかいも', translation: 'Muchas veces  漢字  ひらがな  カタカナ  Español' },
  { word: 'しかし', translation: 'Pero, sin e mbargo' },
  { word: 'からだにいい', translation: 'Bueno para la salud' },
  { word: 'ケーキ', translation: 'Doctor (utilizado' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'おもいます', translation: 'Creer/Pensar .' },
  { word: 'いいます', translation: 'Decir .' },
  { word: 'かちます', translation: 'Ganar .' },
  { word: 'まけます', translation: 'Perder (el partido,' },
  { word: 'す', translation: '［おまつり が］' },
  { word: 'あります', translation: 'Haber , tener ,' },
  { word: 'やくにたちます', translation: 'Ser útil.' },
  { word: 'うごきます', translation: 'Funcionar, moverse .' },
  { word: 'きをつけます', translation: 'Presta atención ,' },
  { word: 'りゅうがくします', translation: 'Estudiar en el' },
  { word: 'すごい', translation: 'Terrible, maravilloso' },
  { kanji: '本当', word: 'ほんとう', translation: 'Verdad .' },
  { kanji: '嘘', word: 'うそ', translation: 'Mentira .' },
  { kanji: '自動車', word: 'じどうしゃ', translation: 'Automóvil , coche .' },
  { kanji: '交通', word: 'こうつう', translation: 'Transpo rte, trafico .' },
  { kanji: '放送', word: 'ほうそう', translation: 'Transmisión , anuncio.' },
  { word: 'ニュース', translation: 'Noticia.' },
  { word: 'アニメ', translation: 'Comic/caricatura.' },
  { word: 'デザイン', translation: 'Diseño.' },
  { kanji: '夢', word: 'ゆめ', translation: 'Sueño.' },
  { kanji: '天才', word: 'てんさい', translation: 'Genio.' },
  { kanji: '地球', word: 'ちきゅう', translation: 'Tierra.' },
  { kanji: '月', word: 'つき', translation: 'Luna.' },
  { word: 'きっと', translation: 'Sin falta.  漢字  ひらがな  カタカナ  Español' },
  { kanji: '最近', word: 'さいきん', translation: 'Últimamente , estos' },
  { kanji: '多分', word: 'たぶん', translation: 'Probablemente,' },
  { word: 'ほんとうに', translation: 'Realmente.' },
  { word: 'そんなに', translation: 'No tan  (se emplea' },
  { word: 'ひさしぶりですね', translation: '。  ¡Tanto tiempo sin' },
  { kanji: '勿論', word: 'もちろん', translation: 'Naturalmente, p or' },
  { word: 'もうかえらない', translation: '…  Tengo que irme ya …' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'きます', translation: 'Ponerse (una camisa,' },
  { word: 'はきます', translation: 'Ponerse (zapatos,' },
  { word: 'がぶります', translation: 'Ponerse (un' },
  { word: 'かけます', translation: 'Ponerse  (las gafas ,' },
  { word: 'します', translation: 'Ponerse (la corbata) .' },
  { word: 'うまれま', translation: 'す  Nacer.' },
  { word: 'コート', translation: 'Abrigo .' },
  { word: 'スーツ', translation: 'Traje.' },
  { word: 'セーター', translation: 'Suéter .' },
  { kanji: '帽子', word: 'ぼうし', translation: 'Sombrero.' },
  { kanji: '眼鏡', word: 'めがね', translation: 'Anteojos, lentes.' },
  { word: 'ケーキ', translation: 'Torta, Pastel.' },
  { word: 'ロボット', translation: 'Robot.' },
  { word: 'ユーモア', translation: 'Humor.' },
  { kanji: '都合', word: 'つごう', translation: 'Conv eniencia.' },
  { word: 'よく', translation: 'Frecuentemente.' },
  { word: 'えーと', translation: 'Bueno, veamos.' },
  { word: 'おめでとう', translation: '[ございま す]  ¡Felicitacion es!' },
  { kanji: '家賃', word: 'やちん', translation: 'Alquiler de casa .' },
  { word: 'ダイニング', translation: 'キチン Cocina, comedor.' },
  { word: 'では', translation: 'Veamos , bueno .' },
  { kanji: '和室', word: 'わしつ', translation: 'Habitación  de estilo' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'おしいれ', translation: 'Armario de estilo' },
  { kanji: '布団', word: 'ふとん', translation: 'Futón  (se usa tanto' },
  { word: 'アパート', translation: 'Apartame nto.' },
  { word: 'パリ', translation: 'Paris.' },
  { kanji: '長城', word: 'ばんりのちょうじょう', translation: 'La gran mur alla china.' },
  { word: 'アンケート', translation: 'Encuesta.' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'ききます', translation: 'Escuchar  (al profesor).' },
  { word: 'まわします', translation: 'Girar.' },
  { word: 'ひきます', translation: 'Tirar, jalar.' },
  { word: 'かえます', translation: 'Cambiar.' },
  { word: 'さわります', translation: 'Tocar (una puerta).' },
  { word: 'でます', translation: '［おつりが ～］' },
  { word: 'でます', translation: 'Salir  (el cambio ).' },
  { word: 'あるきます', translation: 'Caminar.' },
  { word: 'わたります', translation: 'Cruzar un puente.' },
  { word: 'まがります', translation: 'Doblar, girar (a la' },
  { word: 'さびしい', translation: 'Solitario.' },
  { kanji: '音', word: 'おと', translation: 'Sonido.' },
  { word: 'サイズ', translation: 'Tamaño, talla.' },
  { kanji: '故障', word: 'こしょう', translation: 'Avería .' },
  { kanji: '道', word: 'みち', translation: 'Calle, camino.' },
  { kanji: '交差点', word: 'こうさてん', translation: 'Cruce.' },
  { kanji: '信号', word: 'しんごう', translation: 'Semáforos .' },
  { kanji: '角', word: 'かど', translation: 'Esquina.' },
  { kanji: '橋', word: 'はし', translation: 'Puente.' },
  { kanji: '駐車場', word: 'ちゅうしゃじょう', translation: 'Estacionamiento.' },
  { kanji: '建物', word: 'たてもの', translation: 'Edificio.' },
  { word: 'なんかいも', translation: 'Muchas veces.' },
  { kanji: '聖徳太子', word: 'しょうとくたいし', translation: 'Príncipe Shotoku (574' },
  { kanji: '法隆寺', word: 'ほうりゅうじ', translation: 'Horyuji (templo' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'くれます', translation: 'Dar (a mí).' },
  { word: 'なおします', translation: 'Reparar, arreglar,' },
  { word: 'つれていきます', translation: 'Llevar (a alguien).' },
  { word: 'つれてきます', translation: 'Traer (a alguien).' },
  { word: 'おくります', translation: 'Acompañar, llevar (a' },
  { word: 'しょうかいします', translation: 'Presentar (a alguien).' },
  { word: 'せつめいします', translation: 'Guía por (una ciudad,' },
  { word: 'おじいさん', translation: 'おじいちゃん   Explicar.' },
  { word: 'おばあさん', translation: 'おばあちゃん   Abuelo, anciano.' },
  { kanji: '旬美', word: 'しゅんび', translation: 'Preparación.' },
  { word: 'ひっこし', translation: 'ひっこし   Mudanza.' },
  { word: 'ホームステイ', translation: 'Hospedaje en casa de' },
  { kanji: '全部', word: 'ぜんぶ', translation: 'Todo.' },
  { word: 'じぶんで', translation: 'Solo.' },
  { word: 'ほかに', translation: 'Además, parte.' },
  { kanji: '日', word: 'ははのひ', translation: 'Dia de la Madre.' },
  { kanji: '漢字', word: 'ひらがな', translation: 'カタカナ  Español' },
  { word: 'かんがえます', translation: 'Pensar, considerar.' },
  { word: 'つきます', translation: 'Llegar.' },
  { word: 'とります', translation: 'Envejecer.' },
  { word: 'たります', translation: 'Ser suficiente.' },
  { kanji: '田舎', word: 'いなか', translation: 'Zona rural, pueblo' },
  { word: 'チャンス', translation: 'Chance, oportunidad.' },
  { kanji: '億', word: 'おく', translation: 'Cien millones.' },
  { word: 'もしもし', translation: 'Hola, aló (usado para' },
  { kanji: '転勤', word: 'てんきん', translation: 'Traslado.' },
  { word: 'こと', translation: 'Cosa, asunto ( ～のこ' },
  { kanji: '暇', word: 'ひま', translation: 'Tiempo libre.' },
  { word: 'おせわになりました', translation: 'Muchas gracias por' },
  { word: 'かんばります', translation: 'Esforzarse, tener' },
  { word: 'どうぞお', translation: '元気で どうぞおげんきで   Que siga bien/Que le' }
]
