import { Word } from './interfaces'

export const words: Word[] = [
  // Comienzo de Leccion 1
  { kanji: '漢字', kana: 'かんじ', translation: 'Kanji' },
  { kana: 'ひらがな', translation: 'Hiragana' },
  { kana: 'カタカナ', translation: 'Katakana' },
  { kanji: '始めましょう', kana: 'はじめましょう', translation: 'Vamos a empezar.' },
  { kanji: '終りましょう', kana: 'おわりましょう', translation: 'Vamos a terminar.' },
  { kanji: '休みましょう', kana: 'やすみましょう', translation: 'Vamos a descansar.' },
  { kanji: '一度', kana: 'いちど', translation: 'De nuevo' },
  { kana: 'もう', translation: 'Ya.' },
  { kanji: 'もう一度', kana: 'もういちど', translation: 'Una vez más.' },
  { kanji: '名前', kana: 'なまえ', translation: 'Nombre.' },
  { kanji: '試験', kana: 'しけん', translation: 'Examen.' },
  { kanji: '宿題', kana: 'しゅくだい', translation: 'Tarea.' },
  { kanji: '質問', kana: 'しつもん', translation: 'Pregunta.' },
  { kanji: '答え', kana: 'こたえ', translation: 'Respuesta.' },
  { kanji: '例', kana: 'れい', translation: 'Ejemplo.' },
  { kanji: '分かりますか？', kana: 'わかりますか', translation: '¿Entiendes?' },
  { kanji: '分かります', kana: 'わかります', translation: 'Entiendo.' },
  { kanji: '分かりません', kana: 'わかりません', translation: 'No entiendo.' },
  { kana: 'けっこうです', translation: 'Está bien.' },
  { kanji: '駄目です', kana: 'だめです', translation: 'Está mal.' },
  { kana: 'おはようございます ', translation: 'Buenos Días.' },
  { kanji: '今日は', kana: 'こんにちは', translation: 'Hola.' },
  { kanji: '今晩は', kana: 'こんばんは', translation: 'Hola, buenas tardes/noches.' },
  { kanji: 'お休みなさい', kana: 'おやすみなさい', translation: 'Buenas noches (antes de dormir)' },
  { kanji: '左様なら', kana: 'さようなら', translation: 'Chau.' },
  { kanji: 'お早うございます', kana: 'ありがとうございます', translation: 'Muchas gracias.' },
  { kana: 'すみません', translation: 'Disculpa, perdón.' },
  { kana: 'おねがいします', translation: 'Por favor.' },
  { kanji: '零', kana: 'れい', translation: '0.' },
  { kana: 'ゼロ', translation: '0.' },
  { kanji: '一', kana: 'いち', translation: '1.' },
  { kanji: '二', kana: 'に', translation: '2.' },
  { kanji: '三', kana: 'さん', translation: '3.' },
  { kanji: '午', kana: 'ご', translation: '5.' },
  { kanji: '六', kana: 'ろく', translation: '6.' },
  { kanji: '八', kana: 'はち', translation: '8.' },
  { kanji: '九', kana: 'きゅう', translation: '9.' },
  { kanji: '十', kana: 'じゅう', translation: '10.' },
  { kanji: '私', kana: 'わたし', translation: 'Yo.' },
  { kanji: '私', kana: 'あたし', translation: 'Yo (en mujer, casual).' },
  { kanji: '僕', kana: 'ぼく', translation: 'Yo (en hombre, casual).' },
  { kanji: '私達', kana: 'わたしたち', translation: 'Nosotros.' },
  { kanji: 'あなた達', kana: 'あなたたち', translation: 'Ustedes.' },
  { kanji: '彼達', kana: 'かれたち', translation: 'Ellos.' },
  { kanji: '彼女達', kana: 'かのじょたち', translation: 'Ellas.' },
  { kanji: '貴方', kana: 'あなた', translation: 'Tu.' },
  { kanji: 'あの人', kana: 'あのひと', translation: 'Aquella Persona .' },
  { kanji: 'あの方', kana: 'あのかた', translation: 'Aquella Persona (formal)' },
  { kanji: '皆さん', kana: 'みなさん', translation: 'Todos.' },
  { kana: '~さん', translation: 'Sr. | Sra. | Srta.' },
  { kana: '~ちゃん', translation: 'Diminutivo afectuoso (usualmente para niñas o amigos cercanos)' },
  { kana: '~くん', translation: 'Diminutivo afectuoso (usualmente para niños, hombres jóvenes o amigos cercanos)' },
  { kanji: '人', kana: '~じん', translation: '~Nacionalidad' },
  { kanji: '先生', kana: 'せんせい', translation: 'Maestro, profesor (en 2da persona).' },
  { kanji: '教師', kana: 'きょうし', translation: 'Maestro, profesor (en 1era persona).' },
  { kanji: '学生', kana: 'がくせい', translation: 'Estudiante.' },
  { kanji: '~社員', kana: '~しゃいん', translation: 'Empleado de ~.(se usa junto al nombre de la empresa, por ejemplo: ソニーのしゃいん)' },
  { kanji: '会社員', kana: 'かいしゃいん', translation: 'Empleado de una empresa.' },
  { kanji: '銀行員', kana: 'ぎんこういん', translation: 'Banquero.' },
  { kanji: '医者', kana: 'いしゃ', translation: 'Medico.' },
  { kanji: '研究者', kana: 'けんきゅうしゃ', translation: 'Investigador.' },
  { kana: 'エンジニア', translation: 'Ingeniero.' },
  { kanji: '大学', kana: 'だいがく', translation: 'Universidad.' },
  { kanji: '病院', kana: 'びょういん', translation: 'Hospital.' },
  { kanji: '電気', kana: 'でんき', translation: 'Electricidad.' },
  { kanji: '誰', kana: 'だれ', translation: '¿Quién?.' },
  { kanji: '何方', kana: 'どなた', translation: '¿Quién? (formal).' },
  { kanji: '何歳', kana: 'なんさい', translation: 'Cuántos años .' },
  { kanji: '~才/歳', kana: '~さい', translation: '~Años de edad' },
  { kana: 'おいくつ', translation: 'Cuantos años' },
  { kana: 'はい', translation: 'Si.' },
  { kana: 'いいえ', translation: 'No.' },
  { kana: 'しつれいですが', translation: 'Perdóname, pero...' },
  { kana: 'おなまえは？', translation: '¿Cómo se llama? /¿Cual es su nombre?' },
  { kanji: '初めまして', kana: 'はじめまして', translation: 'Encantado de conocerte.' },
  { kana: 'よろしくおねがいします', translation: 'Por favor, cuída de mí, Espero contar con tu ayuda.' },
  // Final de Leccion 01

  // Principio de Leccion 02
  { kana: 'これ', translation: 'Esto. | Este. | Esta.' },
  { kana: 'それ', translation: 'Eso. | Ese. | Esa.' },
  { kana: 'あれ', translation: 'Aquel. | Aquello. | Aquella.' },
  { kana: 'この~', translation: 'Este ~. | Esta ~.' },
  { kana: 'その~', translation: 'Ese ~. | Esa ~.' },
  { kana: 'あの~', translation: 'Aquel ~. | Aquella ~' },
  { kanji: '本', kana: 'ほん', translation: 'Libro.' },
  { kanji: '辞書', kana: 'じしょ', translation: 'Diccionario.' },
  { kanji: '雑誌', kana: 'ざっし', translation: 'Revista.' },
  { kanji: '新聞', kana: 'しんぶん', translation: 'Periódico.' },
  { kana: 'ノート', translation: 'Cuaderno.' },
  { kanji: '手帳', kana: 'てちょう', translation: 'Agenda.' },
  { kanji: '名刺', kana: 'めいし', translation: 'Tarjeta de presentación.' },
  { kana: 'カード', translation: 'Tarjeta.' },
  { kana: 'テレホンカード', translation: 'Tarjeta de teléfono.' },
  { kanji: '鉛筆', kana: 'えんぴつ', translation: 'Lápiz.' },
  { kana: 'ボールペン', translation: 'Bolígrafo.' },
  { kana: 'シャープペンシル', translation: 'Lápiz mecánico.' },
  { kanji: '鍵', kana: 'かぎ', translation: 'Llave.' },
  { kanji: '時計', kana: 'とけい', translation: 'Reloj.' },
  { kanji: '傘', kana: 'かさ', translation: 'Paragua/Sombrilla.' },
  { kanji: '鞄', kana: 'かばん', translation: 'Bolso, maleta.' },
  { kana: 'CD', translation: 'CD' },
  { kana: 'カセットテープ', translation: 'Cinta de casete.' },
  { kana: 'テープレコーダー', translation: 'Grabadora de casete.' },
  { kana: 'テレビ', translation: 'Televisión.' },
  { kana: 'ラジオ', translation: 'Radio.' },
  { kana: 'カメラ', translation: 'Cámara.' },
  { kana: 'コンピューター', translation: 'Computadora.' },
  { kana: 'パソコン', translation: 'Computadora.' },
  { kanji: '自動車', kana: 'じどうしゃ', translation: 'Automóvil.' },
  { kanji: '車', kana: 'くるま', translation: 'Auto.' },
  { kanji: '机', kana: 'つくえ', translation: 'Escritorio.' },
  { kanji: '椅子', kana: 'いす', translation: 'Silla.' },
  { kana: 'チョコレート', translation: 'Chocolate.' },
  { kana: 'コーヒー', translation: 'Café.' },
  { kanji: '英語', kana: 'えいご', translation: 'El idioma inglés.' },
  { kanji: '日本語', kana: 'にほんご', translation: 'El idioma japonés.' },
  { kanji: '~語', kana: '~ご', translation: '~Idioma' },
  { kanji: '何', kana: 'なん', translation: 'Qué.' },
  { kana: 'そう', translation: 'Si, eso.' },
  { kanji: '違います', kana: 'ちがいます', translation: 'No es así./Equivocado.' },
  { kana: 'あのう', translation: 'Eh…, esto… (lit . “mmm”).' },
  { kana: 'えっ', translation: '¿Cómo?' },
  { kana: 'ほんのきもちです', translation: 'Es solo un pequeño gesto' },
  { kana: 'どうぞ', translation: 'Adelante.' },
  { kana: 'どうも', translation: 'Gracias.' },
  { kana: 'どうもありがとうございます', translation: 'Muchísimas gracias.' },
  { kana: 'これから', translation: 'Desde ahora' },
  { kanji: 'お世話になります', kana: 'おせわになります', translation: 'Gracias por su ayuda | Estoy en sus manos.' },
  { kana: 'こちらこそ', translation: 'Igualmente' },
  // Final de Leccion 02

  // Comienzo de Leccion 03
  { kana: 'ここ', translation: 'Aquí,  en este lugar.' },
  { kana: 'そこ', translation: 'Ahí, en ese lugar.' },
  { kana: 'あそこ', translation: 'Allí, en aquel lugar.' },
  { kana: 'どこ', translation: '¿Donde? | ¿Qué lugar?' },
  { kana: 'こちら', translation: 'Aquí, este lugar (formal)' },
  { kana: 'そちら', translation: 'Ahí, ese lugar (formal).' },
  { kana: 'あちら', translation: 'Allí, aquel lugar (fomal)' },
  { kana: 'どちら', translation: '¿Dónde? | ¿Qué lugar? (formal)' },
  { kanji: '教室', kana: 'きょうしつ', translation: 'Aula.' },
  { kanji: '食堂', kana: 'しょくどう', translation: 'Comedor.' },
  { kanji: '事務所', kana: 'じむしょ', translation: 'Oficina.' },
  { kanji: '会議室', kana: 'かいぎしつ', translation: 'Sala de reuniones.' },
  { kanji: '受付', kana: 'うけつけ', translation: 'Recepción.' },
  { kana: 'ロビー', translation: 'Lobby.' },
  { kanji: '部屋', kana: 'へや', translation: 'Habitación, cuarto.' },
  { kana: 'トイレ', translation: 'Baño' },
  { kanji: 'お手洗い', kana: 'おてあらい', translation: 'Lavamanos' },
  { kanji: '階段', kana: 'かいだん', translation: 'Escalera (manual).' },
  { kana: 'エレベーター', translation: 'Ascensor, elevador.' },
  { kana: 'エスカレーター', translation: 'Escalera mecánica.' },
  { kanji: '煙草', kana: 'たばこ', translation: 'Tabaco.' },
  { kanji: '場', kana: 'うりば', translation: 'Sección.' },
  { kanji: '地下', kana: 'ちか', translation: 'Subsuelo, sótano.' },
  { kanji: '何階', kana: 'なんがい', translation: 'Que piso.' },
  { kanji: '円', kana: 'えん', translation: 'Yenes' },
  { kanji: '国', kana: 'くに', translation: 'Pais.' },
  { kanji: '会社', kana: 'かいしゃ', translation: 'Trabajo.' },
  { kanji: '家', kana: 'うち', translation: 'Casa (1era persona).' },
  { kanji: '家', kana: 'いえ', translation: 'Casa (2da persona).' },
  { kanji: '電話', kana: 'でんわ', translation: 'Teléfono, llamada.' },
  { kanji: '靴', kana: 'くつ', translation: 'Zapato.' },
  { kana: 'ネクタイ', translation: 'Corbata.' },
  { kana: 'ワイン', translation: 'Vino.' },
  { kana: 'いくら', translation: 'Cuanto.' },
  { kanji: '百', kana: 'ひゃく', translation: '100.' },
  { kanji: '千', kana: 'せん', translation: '1.000.' },
  { kanji: '万', kana: 'まん', translation: '10.000.' },
  { kana: 'すみません', translation: 'Perdón, disculpa.' },
  { kana: 'でございます', translation: 'Verbo desu en formal.' },
  { kanji: '見せて', kana: 'みせて', translation: 'Muestrame' },
  { kanji: '下さい', kana: 'ください', translation: 'Por favor' },
  { kana: 'じゃ', translation: 'Bueno, entonces.' },
  // Final de Leccion 03

  // Comienzo de Leccion 04
  { kanji: '置きます', kana: 'おきます', translation: 'Despertarse.' },
  { kanji: '寝ます', kana: 'ねます', translation: 'Acostarse, irse a la cama.' },
  { kanji: '働きます', kana: 'はたらきます', translation: 'Trabajar.' },
  { kanji: '休みます', kana: 'やすみます', translation: 'Descansar , estar de "vacaciones"' },
  { kanji: '勉強します', kana: 'べんきょうします', translation: 'Estudiar.' },
  { kanji: '終わります', kana: 'おわります', translation: 'Terminar.' },
  { kana: 'デパート', translation: 'Tienda departamental .' },
  { kanji: '銀行', kana: 'ぎんこう', translation: 'Banco , institución financiera.' },
  { kanji: '郵便局', kana: 'ゆうびんきょく', translation: 'Oficina de correo.' },
  { kanji: '図書館', kana: 'としょかん', translation: 'Biblioteca.' },
  { kanji: '美術館', kana: 'びじゅつかん', translation: 'Museo de arte.' },
  { kanji: '今', kana: 'いま', translation: 'Ahora.' },
  { kanji: '~時', kana: '', translation: 'Las ~ horas.' },
  { kanji: '~分', kana: 'ふん', translation: '~ minutos' },
  { kanji: '~半', kana: '', translation: '~ y media' },
  { kanji: '何時', kana: 'なんじ', translation: 'Qué hora.' },
  { kanji: '何分', kana: 'なんぷん', translation: 'Qué minutos.' },
  { kanji: '午前', kana: 'ごぜん', translation: 'a.m., en la mañana.' },
  { kanji: '午後', kana: 'ごご', translation: 'p.m., en la tarde.' },
  { kanji: '朝', kana: 'あさ', translation: 'La mañana.' },
  { kanji: '昼', kana: 'ひる', translation: 'El medio dia, la tarde.' },
  { kanji: '夜', kana: 'よる', translation: 'La noche.' },
  { kanji: '晩', kana: 'はん', translation: 'La noche.' },
  { kanji: '一昨日', kana: 'おととい', translation: 'Antes de ayer.' },
  { kanji: '昨日', kana: 'きのう', translation: 'Ayer.' },
  { kanji: '今日', kana: 'きょう', translation: 'Hoy.' },
  { kanji: '明日', kana: 'あした', translation: 'Mañana.' },
  { kanji: '明後日', kana: 'あさって', translation: 'Pasado mañana.' },
  { kanji: '今朝', kana: 'けさ', translation: 'Esta mañana.' },
  { kanji: '今晩', kana: 'こんばん', translation: 'Esta noche.' },
  { kanji: '休み', kana: 'やすみ', translation: 'Descanso , dia libre, dia de descanso' },
  { kanji: '昼休み', kana: 'ひるやすみ', translation: 'Hora del almuerzo/Descanso del medio dia,' },
  { kanji: '毎朝', kana: 'まいあさ', translation: 'Todas las mañanas.' },
  { kanji: '毎晩', kana: 'まいばん', translation: 'Todas las noches.' },
  { kanji: '毎日', kana: 'まいにち', translation: 'Todos los días.' },
  { kanji: '月曜日', kana: 'げつようび', translation: 'Lunes.' },
  { kanji: '火曜日', kana: 'かようび', translation: 'Martes.' },
  { kanji: '水曜日', kana: 'すいようび', translation: 'Miercoles.' },
  { kanji: '木曜日', kana: 'もくようび', translation: 'Jueves.' },
  { kanji: '金曜日', kana: 'きんようび', translation: 'Viernes.' },
  { kanji: '土曜日', kana: 'どようび', translation: 'Sábado.' },
  { kanji: '日曜日', kana: 'にちようび', translation: 'Domingo.' },
  { kanji: '何曜日', kana: 'なんようび', translation: 'Qué dia.' },
  { kanji: '番号', kana: 'なんばん', translation: 'Qué número.' },
  { kana: '~から', translation: '~desde' },
  { kana: '~まで', translation: '~hasta' },
  { kana: '~と', translation: '~y' },
  { kana: 'そちら', translation: 'Ese lugar.' },
  { kanji: '大変ですね', kana: 'たいへんですね', translation: '¡Qué duro! ¡Cuánto  lo siento!' },
  { kana: 'えーと', translation: 'Bueno, déjame ver.' },
  { kanji: 'お願いします', kana: 'おねがいします', translation: 'Por favor.' },
  { kanji: '畏まりました', kana: 'かしこまりました', translation: 'Ciertamente .' },
  { kanji: 'お問い合わせの', kana: 'おといあわせの', translation: 'El número consultado.' },
  { kana: 'ありがとうごさいした', translation: ' Muchas gracias por lo brindado. ' },
  // Final de Leccion 04

  // Inicio de Leccion 05
  { kanji: '行きます', kana: 'いきます', translation: 'Ir.' },
  { kanji: '来ます', kana: 'きます', translation: 'Venir.' },
  { kanji: '帰ります', kana: 'かえります', translation: 'Volver, regresar, irse' },
  { kanji: '学校', kana: 'がっこう', translation: 'Escuela.' },
  { kana: 'スーパー', translation: 'Supermercado.' },
  { kanji: '駅', kana: 'えき', translation: 'Estación.' },
  { kanji: '飛行機', kana: 'ひこうき', translation: 'Avión.' },
  { kanji: '船', kana: 'ふね', translation: 'Buque, barco.' },
  { kanji: '電車', kana: 'でんしゃ', translation: 'Tren  eléctrico.' },
  { kanji: '鉄', kana: 'ちかてつ', translation: 'Subterráneo' },
  { kanji: '新幹線', kana: 'しんかんせん', translation: 'Tren Bala.' },
  { kana: 'バス', translation: 'Autobús (Micro).' },
  { kana: 'タクシー', translation: 'Taxi.' },
  { kanji: '車', kana: 'じてんしゃ', translation: 'Bicicleta.' },
  { kanji: '歩いて', kana: 'あるいて', translation: 'A pie, caminando.' },
  { kanji: '人', kana: 'ひと', translation: 'Persona, gente.' },
  { kanji: '友達', kana: 'ともだち', translation: 'Amigo(s).' },
  { kanji: '彼', kana: 'かれ', translation: 'El, novio.' },
  { kanji: '彼女', kana: 'かのじょ', translation: 'Ella, novia.' },
  { kanji: '家族', kana: 'かぞく', translation: 'Familia.' },
  { kanji: '一人で', kana: 'ひとりで', translation: 'Solitario .' },
  { kanji: '先週', kana: 'せんしゅう', translation: 'La semana pasada .' },
  { kanji: '今週', kana: 'こんしゅう', translation: 'Esta semana.' },
  { kanji: '来週', kana: 'らいしゅう', translation: ', la próxima semana.' },
  { kanji: '先月', kana: 'せんげつ', translation: 'El mes pasado.' },
  { kanji: '今月', kana: 'こんげつ', translation: 'Este mes' },
  { kanji: '来月', kana: 'らいげつ', translation: 'El próximo mes.' },
  { kanji: '去年', kana: 'きょうねん', translation: 'El año pasado.' },
  { kanji: '今年', kana: 'ことし', translation: 'Este año , el año' },
  { kanji: '来年', kana: 'らいねん', translation: 'El año que viene, el proximo año' },
  { kanji: '何月', kana: 'なんがつ', translation: 'Qué mes.' },
  { kanji: '一日', kana: 'ついたち', translation: 'Dia 1 del mes.' },
  { kanji: '二日', kana: 'ふつか', translation: 'Dia 2 del mes.' },
  { kanji: '三日', kana: 'みっか', translation: 'Dia 3 del mes.' },
  { kanji: '四日', kana: 'よっか', translation: 'Dia 4 del mes.' },
  { kanji: '五日', kana: 'いつか', translation: 'Dia 5 del mes.' },
  { kanji: '六日', kana: 'むいか', translation: 'Dia 6 del mes.' },
  { kanji: '七日', kana: 'なのか', translation: 'Dia 7 del mes.' },
  { kanji: '八日', kana: 'ようか', translation: 'Dia 8 del mes.' },
  { kanji: '九日', kana: 'ここのか', translation: 'Dia 9 del mes.' },
  { kanji: '十日', kana: 'とおか', translation: 'Dia 10 del mes.' },
  { kanji: '十四日', kana: 'じゅうよっか', translation: 'Dia 14 del mes.' },
  { kanji: '二十日', kana: 'はつか', translation: 'Dia 20 del mes.' },
  { kanji: '二十四日', kana: 'にじゅうよっか', translation: 'Dia 24 del mes.' },
  { kanji: '何日', kana: 'なんにち', translation: 'Qué dia.' },
  { kana: 'いつ', translation: '¿Cuándo?.' },
  { kanji: '誕生日', kana: 'たんじょうび', translation: 'Cumpleaños.' },
  { kanji: '普通', kana: 'ふつう', translation: 'Tren local.' },
  { kanji: '急行', kana: 'きゅうこう', translation: 'Tren rápido.' },
  { kanji: '特急', kana: 'とっきゅう', translation: 'Tren exprés.' },
  { kana: 'つぎの', translation: 'Siguiente.' },
  { kana: 'どういたしまして', translation: 'De nada.' },
  // Final de leccion 05

  // Inicio de Leccion 06
  { kana: 'きります', translation: 'Cortar' },
  { kana: 'おくります', translation: 'Enviar' },
  { kana: 'あげます', translation: 'Dar' },
  { kana: 'もらいます', translation: 'Recibir' },
  { kana: 'かします', translation: 'Prestar' },
  { kana: 'かります', translation: 'Pedir prestado' },
  { kana: 'おしえます', translation: 'Enseñar' },
  { kana: 'ならいます', translation: 'Aprender' },
  { kanji: '手', kana: 'て', translation: 'Mano' },
  { kana: 'はし', translation: 'Palillos chinos' },
  { kana: 'スプーン', translation: 'Cuchara' },
  { kana: 'ナイフ', translation: 'Cuchillo' },
  { kana: 'フォーク', translation: 'Tenedor' },
  { kana: 'はさみ', translation: 'Tijeras' },
  { kana: 'ファクス', translation: 'Fax' },
  { kana: 'ワープロ', translation: 'Procesador de texto' },
  { kana: 'パソコン', translation: 'Comp utador a personal' },
  { kana: 'パンチ', translation: 'Golpe / Puñetazo' },
  { kana: 'ホッチキス', translation: 'Engrapadora' },
  { kana: 'セロテープ', translation: 'Cinta s cotch' },
  { kana: 'けし', translation: 'ゴマ  Goma de borrar' },
  { kanji: '紙', kana: 'かみ', translation: 'Papel' },
  { kanji: '花', kana: 'はな', translation: 'Flor' },
  { kana: 'シャツ', translation: 'Camisa' },
  { kana: 'プレゼント', translation: 'Presente, regalo' },
  { kanji: '荷物', kana: 'にもつ', translation: 'Equipaje, paquete' },
  { kanji: '金', kana: 'おかね', translation: 'Dinero' },
  { kanji: '切符', kana: 'きっぷ', translation: 'Ticket, boleto' },
  { kana: 'クリスマス', translation: 'Navidad' },
  { kanji: '父', kana: 'ちち', translation: '(Mi) Papá' },
  { kanji: '母', kana: 'はは', translation: '(Mi)  Mamá' },
  { kana: 'おとうさん', translation: 'Padre (de alguien)' },
  { kana: 'おかあさん', translation: 'Madre (de alguien)' },
  { kana: 'もう', translation: 'Ya' },
  { kana: 'まだ', translation: 'Todavía  no' },
  // Final de leccion 06

  // Inicio de Leccion 07
  { kana: 'これから', translation: 'Desde ahora' },
  { kana: 'ね', translation: '¡Qué  bonito  [~]!' },
  { kana: 'ごめん', translation: 'ください   Disculpe. ¿Hay' },
  { kana: 'いらっしゃい', translation: 'Qué bien que hayas' },
  { kana: 'どうぞ', translation: 'おあがり' },
  { kana: 'ください', translation: 'Pase  / Adelante  por' },
  { kana: 'りょこう', translation: 'Viaje' },
  { kana: 'おみやげ', translation: 'Souv enir' },

  { kana: 'おおきい', translation: 'Grande / Largo' },
  { kana: 'ちいさい', translation: 'Pequeño' },
  { kana: 'あたらしい', translation: 'Nuevo' },
  { kana: 'ふるい', translation: 'Viejo' },
  { kana: 'わるい', translation: 'Malo' },
  { kana: 'あつい', translation: 'Caliente' },
  { kana: 'さむい', translation: 'frío (en referencia a' },
  { kana: 'つめたい', translation: 'frío (refiriéndose al' },
  { kana: 'むずかしい', translation: 'Difícil' },
  { kana: 'やさしい', translation: 'Fácil / Amable' },
  { kana: 'たかい', translation: 'Alto / Caro.' },
  { kana: 'やすい', translation: 'Barato' },
  { kana: 'ひくい', translation: 'Bajo' },
  { kana: 'おもしろい', translation: 'Interesante' },
  { kana: 'おいしい', translation: 'Delicioso' },
  { kana: 'いそがしい', translation: 'Ocupado' },
  { kana: 'たのしい', translation: 'Divertido' },
  { kana: 'しろい', translation: 'Blanco' },
  { kana: 'くろい', translation: 'Negro' },
  { kana: 'あかい', translation: 'Rojo  漢字  ひらがな  かたかな  Español' },
  { kana: 'あおい', translation: 'Azul' },
  { kanji: '桜', kana: 'さくら', translation: 'Flores de cerezo' },
  { kanji: '山', kana: 'やま', translation: 'Montaña' },
  { kanji: '町', kana: 'まち', translation: 'Ciudad' },
  { kanji: '物', kana: 'たべもの', translation: 'Comida' },
  { kanji: '車', kana: 'くるま', translation: 'Carro / Auto' },
  { kanji: '所', kana: 'ところ', translation: 'Lugar' },
  { kanji: '寮', kana: 'りょう', translation: 'Dormitorio' },
  { kanji: '勉強', kana: 'べんきょう', translation: 'Estudio' },
  { kanji: '生活', kana: 'せいかつ', translation: 'Vida (diaria)' },
  { kanji: '仕事', kana: 'しごと', translation: 'Trabajo' },
  { kana: 'どう', translation: 'cómo' },
  { kana: 'どんな', translation: 'Qué tipo / Qué cosa' },
  { kana: 'どれ', translation: 'cuál ( entre  tres o' },
  { kana: 'とても', translation: 'Mucho' },
  { kana: 'あまり', translation: 'Muy poco (se usa en' },
  { kana: 'そして', translation: 'Entonces, y (se utiliza' },
  { kana: 'おげんきですか', translation: '¿Cómo estás?' },
  { kana: 'そうですね', translation: '¡Oh, si!' },
  { kanji: '生活', kana: 'にほんのせいかつ', translation: 'Vida en Japón' },
  { kana: 'もう', translation: '一杯ぱい' },
  { kana: 'いかが', translation: 'ですか  ［～、 ］' },
  { kana: 'もう', translation: 'いっぱ' },
  { kana: 'いかが', translation: 'ですか   ¿No quieres otra taza' },
  { kana: 'いいえ', translation: 'けっこうです   No, gracias' },
  { kana: 'そろそろ', translation: '失礼します。  そろそろ' },
  { kana: 'また', translation: 'いらっしゃてください   Por favor vuelvan' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'わかります', translation: '［が］  Entiendo' },
  { kana: 'あります', translation: '［が］  Haber' },
  { kana: 'じょうず', translation: '［な］   Bueno en' },
  { kanji: '料理', kana: 'りょうり', translation: 'Comida, cocina' },
  { kanji: '物', kana: 'のみもの', translation: 'Bebidas' },
  { kana: 'スポーツ', translation: 'Deportes' },
  { kanji: '柳生', kana: 'やぎゅう', translation: 'Baseball' },
  { kana: 'ダンス', translation: 'Baile' },
  { kanji: '音楽', kana: 'おんがく', translation: 'Música' },
  { kanji: '歌', kana: 'うた', translation: 'Canción' },
  { kana: 'クラシック', translation: 'Clásica' },
  { kana: 'ジャズ', translation: 'Jazz' },
  { kana: 'コンサート', translation: 'Concierto' },
  { kana: 'カラオケ', translation: 'Karaoke' },
  { kanji: '歌舞伎', kana: 'かぶき', translation: 'Teatro tradicional' },
  { kanji: '絵', kana: 'え', translation: 'Imagen, dibujar' },
  { kanji: '字', kana: 'じ', translation: 'Letra, carácter' },
  { kanji: '漢字', kana: 'かんじ', translation: 'Kanji' },
  { kana: 'ひらがな', translation: 'Hiragana' },
  { kana: 'カタカナ', translation: 'Katakana' },
  { kanji: '字', kana: 'ローマじ', translation: 'Romaji' },
  { kanji: '金', kana: 'こまかいおかね', translation: 'Cambio pequeño' },
  { kana: 'チケット', translation: 'Ticket' },
  { kanji: '時間', kana: 'じかん', translation: 'Tiempo' },
  { kanji: '用事', kana: 'ようじ', translation: 'Algo que hacer,' },
  { kanji: '約束', kana: 'やくそく', translation: 'Promesa, cita' },
  { kanji: '主人', kana: 'ごしゅじん', translation: 'Esposo (de alguien)  漢字  ひらがな  カタカナ  Español' },
  { kanji: '主人', kana: 'おっと', translation: '/しゅじん   Esposo (mío)' },
  { kana: 'おくさん', translation: 'Esposa (de alguien)' },
  { kanji: '家内', kana: 'つま', translation: '/かない   Esposa (mía)' },
  { kanji: '子供', kana: 'こども', translation: 'Niño' },
  { kana: 'よく', translation: 'A menudo' },
  { kana: 'だいたい', translation: 'La mayoría' },
  { kana: 'たくさん', translation: 'Mucho' },
  { kana: 'すこし', translation: 'Un poco' },
  { kanji: '全然', kana: 'ぜんぜん', translation: 'Nada' },
  { kana: 'はやく', translation: 'Rápido' },
  { kana: 'どうして', translation: '¿Por qué?' },
  { kana: 'ざんねんです', translation: '［ね］  Que lastima, estoy' },
  { kana: 'すみません', translation: 'Perdón' },
  { kana: 'もしもし', translation: 'Hola (usado solo en' },
  { kana: 'ああ', translation: 'Oh' },
  { kana: 'いっしょに', translation: 'いかがですか。   ¿Te gustaría unirte' },
  { kana: 'だめですか', translation: '¿Así que no puedes?' },
  { kana: 'またこんど', translation: 'La próxima vez' },
  { kanji: '生活', kana: 'おねがいします', translation: 'Por favor' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'あります', translation: '［が］  Haber  (cosas' },
  { kanji: '人', kana: 'おとこのひと', translation: 'Hombre' },
  { kanji: '人', kana: 'おんなのひと', translation: 'Mujer' },
  { kanji: '子', kana: 'おとこのこ', translation: 'Niño' },
  { kanji: '子', kana: 'おんなの', translation: 'こ  Niña' },
  { kanji: '犬', kana: 'いぬ', translation: 'Perro' },
  { kanji: '猫', kana: 'ねこ', translation: 'Gato' },
  { kanji: '木', kana: 'き', translation: 'Árbol' },
  { kanji: '物', kana: 'もの', translation: 'Cosa' },
  { kana: 'フィルム', translation: 'Película' },
  { kanji: '電池', kana: 'でんち', translation: 'Batería' },
  { kanji: '箱', kana: 'はこ', translation: 'Caja' },
  { kana: 'スイッチ', translation: 'Switch' },
  { kanji: '冷蔵庫', kana: 'れいぞうこ', translation: 'Refri gerador' },
  { kana: 'テーブル', translation: 'Mes a' },
  { kana: 'ベッド', translation: 'Cama' },
  { kanji: '棚', kana: 'たな', translation: 'Estante' },
  { kana: 'ドア', translation: 'Puerta' },
  { kanji: '窓', kana: 'まど', translation: 'Ventana' },
  { kana: 'ポスト', translation: 'Buzón  de correo' },
  { kana: 'ビル', translation: 'Edificio' },
  { kanji: '公園', kana: 'こうえん', translation: 'Parque' },
  { kanji: '喫茶店', kana: 'きっさて', translation: 'ん コーヒー ショップ  Cafetería' },
  { kanji: '本屋', kana: 'ほんや', translation: 'Librería' },
  { kanji: '場', kana: 'のりば', translation: 'Para de t axi, tren,' },
  { kanji: '県', kana: 'けん', translation: 'Prefectura' },
  { kanji: '上', kana: 'うえ', translation: 'Arriba' },
  { kanji: '下', kana: 'した', translation: 'Abajo' },
  { kanji: '前', kana: 'まえ', translation: 'Al frente' },
  { kana: 'うしろ', translation: 'Atrás , detrás 漢字  ひらがな  カタカナ  Español' },
  { kanji: '右', kana: 'みぎ', translation: 'Derecha' },
  { kanji: '左', kana: 'ひだり', translation: 'Izquierda' },
  { kanji: '中', kana: 'なか', translation: 'Adentro' },
  { kanji: '外', kana: 'そと', translation: 'Afuera' },
  { kanji: '隣', kana: 'となり', translation: 'Siguiente' },
  { kana: 'ちかく', translation: 'Cerca' },
  { kanji: '間', kana: 'あいだ', translation: 'Entre' },
  { kana: 'いちばん', translation: '～  El favorito.' },
  { kana: 'うえ', translation: ')  Arriba de todo' },
  { kanji: '棚', kana: 'たな', translation: 'Estante  completo' },
  { kana: 'すみません', translation: '。  Muchas gracias' },
  { kana: 'チリソー', translation: 'ス Salsa de Chile' },
  { kanji: '奥', kana: 'おく', translation: 'El final, o al final' },
  { kana: 'スパイスコーナ', translation: 'ー Sección  de Picantes' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'います', translation: 'Estar (en Japón )' },
  { kana: 'かかりま', translation: 'す  Tomar' },
  { kana: 'やすみます', translation: 'Tomarse un dia' },
  { kana: 'ひとつ', translation: 'Una cosa' },
  { kana: 'ふたつ', translation: 'Dos cosas' },
  { kana: 'みっつ', translation: 'Tres cosas' },
  { kana: 'よっつ', translation: 'Cuatro cosas' },
  { kana: 'いつつ', translation: 'Cinco cosas' },
  { kana: 'むっつ', translation: 'Seis cosas' },
  { kana: 'ななつ', translation: 'Siete cosas' },
  { kana: 'やっつ', translation: 'Ocho cosas' },
  { kana: 'ここのつ', translation: 'Nueve  cosas' },
  { kanji: '十', kana: 'とお', translation: 'Diez cosas' },
  { kana: 'いくつ', translation: '¿Cuántas  cosas ?' },
  { kanji: '一人', kana: 'ひとり', translation: 'Una persona' },
  { kanji: '二人', kana: 'ふたり', translation: 'Dos personas' },
  { kana: 'りんご', translation: 'Manzana' },
  { kana: 'みかん', translation: 'Mandarina' },
  { kana: 'サンドイッ', translation: 'チ Sándwich' },
  { kana: 'カレー', translation: '［ライス ］ Curry de arroz' },
  { kana: 'アイスクリー', translation: 'ム Helado' },
  { kanji: '切手', kana: 'きって', translation: 'Estampillas  漢字  ひらがな  カタカナ  Español' },
  { kanji: '葉書', kana: 'はがき', translation: 'Plantilla de' },
  { kanji: '封筒', kana: 'ふうとう', translation: 'Sobre' },
  { kanji: '速達', kana: 'そくたつ', translation: 'Entrega especial' },
  { kanji: '書留', kana: 'かきとめ', translation: 'Correo' },
  { kanji: '航空便', kana: 'こうくう', translation: 'びん エアメー ル Correo aéreo' },
  { kanji: '船便', kana: 'ふなびん', translation: 'Correo  marino' },
  { kanji: '両親', kana: 'りょうしん', translation: 'Padres' },
  { kanji: '兄弟', kana: 'きょうだ', translation: 'い  Hermanos' },
  { kanji: '兄', kana: 'あに', translation: 'Mi hermano' },
  { kana: 'おにいさん', translation: 'El hermano' },
  { kanji: '姉', kana: 'あね', translation: 'Mi hermana' },
  { kana: 'おねえさ', translation: 'ん  La hermana' },
  { kanji: '弟', kana: 'おとうと', translation: 'Mi hermano' },
  { kana: 'おとうとさん', translation: 'El hermano' },
  { kanji: '妹', kana: 'いもうと', translation: 'Mi hermana' },
  { kana: 'いもうとさ', translation: 'ん  La hermana' },
  { kanji: '外国', kana: 'がいこく', translation: 'País extran jero' },
  { kana: 'ん', translation: '～semanas' },
  { kana: 'チリソー', translation: 'ス ～aproximado' },
  { kana: 'い', translation: '～cuánto  dura' },
  { kana: 'ぜんぶで', translation: 'En total' },
  { kanji: '皆', kana: 'みんな', translation: 'Todos' },
  { kana: 'いらしゃいませ', translation: 'Bienvenido /' },
  { kana: 'おでかけです', translation: 'か  ¿Vas a salir?' },
  { kana: 'ゃい', translation: 'いっていらっしゃ い  Hasta la vista.' },
  { kana: 'いっていきます', translation: 'Me voy - hasta' },
  { kana: 'それから', translation: 'y, además' },
  { kana: 'オーストラリ', translation: 'ア Australia' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'かんたん', translation: '［な］  Fácil' },
  { kana: 'ちかい', translation: 'Cerca' },
  { kana: 'とおい', translation: 'Lejos' },
  { kana: 'はやい', translation: 'Rápido ,' },
  { kana: 'おそい', translation: 'Lento, tarde' },
  { kana: 'あたたか', translation: 'い  Calien te' },
  { kana: 'すずしい', translation: 'Frio' },
  { kana: 'あまい', translation: 'Dulce' },
  { kana: 'からい', translation: 'Picante' },
  { kana: 'おもい', translation: 'Pesado' },
  { kana: 'かるい', translation: 'Liviano' },
  { kanji: '季節', kana: 'きせつ', translation: 'Estaciones' },
  { kanji: '春', kana: 'はる', translation: 'Primavera' },
  { kanji: '夏', kana: 'なつ', translation: 'Verano' },
  { kanji: '秋', kana: 'あき', translation: 'Otoño' },
  { kanji: '冬', kana: 'ふゆ', translation: 'Invierno' },
  { kanji: '天気', kana: 'てんき', translation: 'Clima' },
  { kanji: '雨', kana: 'あめ', translation: 'Lluvia' },
  { kanji: '雪', kana: 'ゆき', translation: 'Nieve' },
  { kana: 'くもり', translation: 'Nublado' },
  { kana: 'ホテル', translation: 'Hotel' },
  { kanji: '空港', kana: 'くうこう', translation: 'Aeropuerto' },
  { kanji: '海', kana: 'うみ', translation: 'Mar, océano' },
  { kanji: '世界', kana: 'せかい', translation: 'Mundo' },
  { kana: 'パーティ', translation: 'ー Fiesta' },
  { kanji: '試験', kana: 'しけん', translation: 'Examen' },
  { kana: 'すきやき', translation: 'Sukiyaki  漢字  ひらがな  カタカナ  Español' },
  { kanji: '刺身', kana: 'さしみ', translation: 'Sashimi' },
  { kana: 'てんぷら', translation: 'Tempura' },
  { kanji: '花', kana: 'いけばな', translation: 'Arreglo floral' },
  { kanji: '紅葉', kana: 'もみじ', translation: 'Maple' },
  { kana: 'どちら', translation: '¿Cuál? (entre' },
  { kana: 'どちらも', translation: 'Ambas' },
  { kana: 'ずっと', translation: 'Con diferencia ,' },
  { kana: 'はじめて', translation: 'Por primera vez' },
  { kana: 'おかえりなさ', translation: 'い  Bienvenido a' },
  { kana: 'すごいですね', translation: '。  Es increíble ,' },
  { kana: 'でも', translation: '¿Pero?' },
  { kana: 'つかれました', translation: 'Estoy cansado.' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'あそびます', translation: 'Disfrutar, jugar' },
  { kana: 'およぎます', translation: 'Nadar' },
  { kana: 'むかえま', translation: 'す  Ir a la reunión ,' },
  { kana: 'つかれます', translation: 'Estoy cansado' },
  { kana: 'だします', translation: '［てがみを～］   Enviar [una' },
  { kana: 'はいります', translation: '［きっさてんに～ ］  Entrar [a una' },
  { kana: 'でます', translation: '［きっさてんを～］   Salir [de una' },
  { kana: 'けっこんします', translation: 'Casarse,' },
  { kana: 'かいものします', translation: 'Hacer shopping' },
  { kana: 'しょくじしま', translation: 'す  comer, cenar' },
  { kana: 'さんぽします', translation: '［こうえんを～ ］  Dar un paseo' },
  { kana: 'ほしい', translation: 'Desear' },
  { kana: 'さびしい', translation: 'Solitario' },
  { kana: 'ひろい', translation: 'Amplio,' },
  { kana: 'せまい', translation: 'Estrecho,' },
  { kanji: '市役所', kana: 'しやくし', translation: 'ょ  Oficina' },
  { kana: 'プール', translation: 'Piscina' },
  { kanji: '川', kana: 'かわ', translation: 'Rio' },
  { kanji: '経済', kana: 'けいざい', translation: 'Economía' },
  { kanji: '美術', kana: 'びじゅつ', translation: 'Bellas artes' },
  { kana: 'つり', translation: 'Pesca' },
  { kana: 'スキー', translation: 'Esquí  漢字  ひらがな  カタカナ  Español' },
  { kanji: '空港', kana: 'くうこう', translation: 'Aeropuerto' },
  { kanji: '会議', kana: 'かいぎ', translation: 'Reunión,' },
  { kanji: '登録', kana: 'とうろく', translation: 'Inscripción' },
  { kanji: '週末', kana: 'しゅうま', translation: 'つ  Fin de semana' },
  { kana: 'なにか', translation: 'Algo' },
  { kana: 'どこか', translation: 'En alguna parte,' },
  { kana: 'おなかがすきました', translation: '(Tengo) hambre' },
  { kana: 'す', translation: 'おなかがいっぱいです   (Estoy) lleno' },
  { kana: 'のどがかわきました', translation: '(Tengo) sed' },
  { kana: 'そうですね', translation: 'Estoy de' },
  { kana: 'そうしましょう', translation: 'Hagámoslo. (se' },
  { kana: 'ごちゅうもんは', translation: '？  ¿Puedo tomar' },
  { kanji: '定食', kana: 'ていしょく', translation: 'Comida' },
  { kana: 'ぎゅうど', translation: 'ん  Gyudon' },
  { kana: 'おまちください', translation: 'Por favor,' },
  { kana: 'べつべつに', translation: 'Por separado' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'つけます', translation: 'Encender' },
  { kana: 'けします', translation: 'Apagar' },
  { kana: 'あけます', translation: 'Abrir' },
  { kana: 'しめます', translation: 'Cerrar' },
  { kana: 'いそぎます', translation: 'Apresurarse' },
  { kana: 'まちます', translation: 'Esperar' },
  { kana: 'とめます', translation: 'Detenerse,' },
  { kana: 'まがりま', translation: 'す  Girar' },
  { kana: 'もちます', translation: 'Mantener' },
  { kana: 'とります', translation: 'Tomar' },
  { kana: 'てつだいます', translation: 'Ayudar (con una' },
  { kana: 'よびます', translation: 'Llamar' },
  { kana: 'ほしい', translation: 'Desear' },
  { kana: 'はなしま', translation: 'す  Hablar,' },
  { kana: 'みせます', translation: 'Mostrar' },
  { kana: 'おしえま', translation: 'す  Decir (una' },
  { kana: 'はじめます', translation: 'Empezar, iniciar' },
  { kana: 'コピーします', translation: 'Copiar' },
  { kana: 'エアコン', translation: 'Aire' },
  { kana: 'パスポート', translation: 'Pasaporte' },
  { kanji: '名前', kana: 'なまえ', translation: 'Nombre' },
  { kanji: '住所', kana: 'じゅうし', translation: 'ょ  Dirección' },
  { kanji: '地図', kana: 'ちず', translation: 'Mapa' },
  { kanji: '塩', kana: 'しお', translation: 'Sal' },
  { kanji: '砂糖', kana: 'さとう', translation: 'Azúcar' },
  { kanji: '方', kana: 'よみかた', translation: 'Cómo leer,' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'ゆっくり', translation: 'Despacio, sin' },
  { kana: 'すぐ', translation: 'Inmediatamente' },
  { kana: 'また', translation: 'De nuevo' },
  { kana: 'あとで', translation: 'Después' },
  { kana: 'もうすこし', translation: 'Un poquito mas' },
  { kana: 'いいですよ', translation: '。  Claro ,' },
  { kana: 'さあ', translation: 'Correcto (se' },
  { kana: 'しんごうをみぎ', translation: 'へ' },
  { kana: 'まっすぐいきます', translation: 'Recto' },
  { kana: 'これでおねがいしま', translation: 'す。  Voy a pagar con' },
  { kana: 'おつり', translation: 'Cambio' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'たちます', translation: 'Pararse' },
  { kana: 'すわります', translation: 'Sentarse' },
  { kana: 'つかいます', translation: 'Usar' },
  { kana: 'おきます', translation: 'Poner' },
  { kana: 'つくります', translation: 'Hacer , Prod ucir' },
  { kana: 'うります', translation: 'Vender' },
  { kana: 'しります', translation: 'Conocer' },
  { kana: 'みます', translation: 'Ir a vivir' },
  { kana: 'けんきゅうします', translation: 'Investigar' },
  { kana: 'しる', translation: 'Saber' },
  { kana: 'しっています', translation: 'Saber / c onocer' },
  { kana: 'しりません', translation: 'No saber / no' },
  { kana: 'すむ', translation: 'Vivir' },
  { kana: 'すんでいます', translation: 'Vivir en ～' },
  { kana: 'けんきゅうします', translation: 'Investigación' },
  { kana: 'カタログ', translation: 'Catalogo' },
  { kanji: '時刻表', kana: 'じこくひょう', translation: 'Horario' },
  { kanji: '服', kana: 'ふく', translation: 'Ropa' },
  { kanji: '製品', kana: 'せいひん', translation: 'Producto' },
  { kana: 'ソフト', translation: 'Software' },
  { kanji: '専門', kana: 'せんもん', translation: 'Especialidad,' },
  { kanji: '歯医者', kana: 'はいしゃ', translation: 'Denti sta' },
  { kanji: '床屋', kana: 'とこや', translation: 'Barbero' },
  { kana: 'プレイガイド', translation: 'Agencia de' },
  { kanji: '独身', kana: 'どくしん', translation: 'Soltero' },
  { kana: 'とくに', translation: 'Especialmente' },
  { kana: 'おもいだします', translation: 'Recordar ,' },
  { kanji: '家族', kana: 'ごかぞく', translation: 'La familia de' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'いらっしゃいます', translation: 'います  de' },
  { kanji: '高校', kana: 'こうこう', translation: 'Escuela' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'のります', translation: '［でんしゃに～］   Montar, subir (a' },
  { kana: 'おります', translation: '［でんしゃを～］   Bajarse (de un' },
  { kana: 'のりかえます', translation: 'Cambiar' },
  { kana: 'あびます', translation: '［シャワー を～］   Tomar (ducha)' },
  { kana: 'いれます', translation: 'Poner, insertar' },
  { kana: 'だします', translation: 'Sacar, expulsar' },
  { kana: 'はいります', translation: '［だいがくに～］   Entrar (a la' },
  { kana: 'でます', translation: '［だいがくを～］   Graduarte (de la' },
  { kana: 'やめます', translation: '［かいしゃを～］   Renunciar o' },
  { kana: 'おします', translation: 'Presionar,' },
  { kana: 'わかい', translation: 'Joven' },
  { kana: 'ながい', translation: 'Largo' },
  { kana: 'みじかい', translation: 'Corto' },
  { kana: 'あかるい', translation: 'Brillante,' },
  { kana: 'くらい', translation: 'Oscuro' },
  { kana: 'せがたかい', translation: 'Alto' },
  { kana: 'あたまがいい', translation: 'Listo, Inteligente' },
  { kanji: '体', kana: 'からだ', translation: 'Cuerpo' },
  { kanji: '頭', kana: 'あたま', translation: 'Cabeza' },
  { kanji: '髪', kana: 'かみ', translation: 'Cabello' },
  { kanji: '顔', kana: 'かお', translation: 'Cara' },
  { kanji: '目', kana: 'め', translation: 'Ojos' },
  { kanji: '耳', kana: 'みみ', translation: 'Oido, oreja' },
  { kanji: '口', kana: 'くち', translation: 'Boca  漢字  ひらがな  かアカナ  Espa ñol' },
  { kanji: '歯', kana: 'は', translation: 'Diente' },
  { kanji: '腹', kana: 'おなか', translation: 'Estomago' },
  { kanji: '足', kana: 'あし', translation: 'Pierna, pie' },
  { kana: 'サービス', translation: 'Servicio' },
  { kana: 'ジョギング', translation: 'Jogging' },
  { kana: 'シャワー', translation: 'Ducha' },
  { kanji: '緑', kana: 'みどり', translation: 'Verde' },
  { kanji: '神社', kana: 'じんじゃ', translation: 'Santuario' },
  { kanji: '留学生', kana: 'りゅうがくせい', translation: 'Estudiante' },
  { kana: 'どうやって', translation: 'De qué manera,' },
  { kana: 'まだまだです', translation: '(No,) Todavía' },
  { kana: 'まず', translation: 'En primer lugar' },
  { kana: 'キャッシュカー', translation: 'ド Tarjeta de' },
  { kanji: '暗証番号', kana: 'あんしょうばんごう', translation: 'Número de' },
  { kana: 'つぎに', translation: 'Siguiente, como' },
  { kanji: '金額', kana: 'きんがく', translation: 'Cantidad de' },
  { kanji: '確認', kana: 'かくにん', translation: 'Confirmación' },
  { kana: 'かくにん', translation: '［をします ］  Confirmar' },
  { kana: 'ボタン', translation: 'Botón' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'おぼえます', translation: 'Memorizar' },
  { kana: 'わすれます', translation: 'Olvidar' },
  { kana: 'なくします', translation: 'Perder' },
  { kana: 'だします', translation: 'Entregar' },
  { kana: 'はらいます', translation: 'Pagar' },
  { kana: 'かえします', translation: 'Devolver' },
  { kana: 'でかけます', translation: 'Salir' },
  { kana: 'ぬぎます', translation: 'Quitarse (ropa,' },
  { kana: 'もっていきます', translation: 'Agarrar,' },
  { kana: 'もってきます', translation: 'Traer' },
  { kana: 'しんぱいします', translation: 'Preocuparse' },
  { kana: 'ざんぎょうします', translation: 'Trabajar h oras' },
  { kana: 'しゅっちょうします', translation: 'Ir de viaje de' },
  { kana: 'のみます', translation: 'Tomar [medicina]' },
  { kana: 'はいります', translation: 'Tomar  [baño]' },
  { kana: 'あぶない', translation: 'Peligroso' },
  { kanji: '問題', kana: 'もんだい', translation: 'Pregunta,' },
  { kana: 'こたえ', translation: 'Respuesta' },
  { kanji: '禁煙', kana: 'きんえん', translation: 'No fumar' },
  { kana: 'ほけんしょう', translation: 'Tarjeta de seguro' },
  { kanji: '風邪', kana: 'かぜ', translation: 'Aire, frio' },
  { kanji: '病気', kana: 'びょうき', translation: 'Enfermedad,' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'かアカナ  Espa ñol' },
  { kanji: '熱', kana: 'ねつ', translation: 'Fiebre' },
  { kanji: '薬', kana: 'くすり', translation: 'Medicina' },
  { kanji: '上着', kana: 'うわぎ', translation: 'Chaqueta' },
  { kanji: '下着', kana: 'したぎ', translation: 'Ropa interior' },
  { kanji: '先生', kana: 'せんせい', translation: 'Doctor (utilizado' },
  { kanji: '神社', kana: 'ですから', translation: 'Por lo tanto' },
  { kanji: '喉', kana: 'のど', translation: 'Garganta' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'のぼります', translation: 'Escalar /Subir' },
  { kana: 'とまります', translation: 'Estar' },
  { kana: 'そうじします', translation: 'Limpiar' },
  { kana: 'せんたくします', translation: 'Lavar  (ropa)' },
  { kana: 'れんしゅうします', translation: 'Practicar' },
  { kana: 'なります', translation: 'なります   Converti rse/volverse' },
  { kana: 'ねむい', translation: 'Adormecido,' },
  { kana: 'つよい', translation: 'Fuerte' },
  { kana: 'よわい', translation: 'Debil' },
  { kana: 'ちょうしがいい', translation: 'Estar en buenas' },
  { kana: 'ちょうしがわるい', translation: 'Estar en malas' },
  { kanji: '調子', kana: 'ちょうし', translation: 'Condicion' },
  { kana: 'ゴルフ', translation: 'Golf' },
  { kanji: '相撲', kana: 'すもう', translation: 'Lucha de Sumo' },
  { kana: 'パチンコ', translation: 'Pinball' },
  { kanji: '茶', kana: 'おちゃ', translation: 'Ceremoni a del te' },
  { kanji: '日', kana: 'ひ', translation: 'Dia, fecha' },
  { kanji: '一度', kana: 'いちど', translation: '1 vez' },
  { kana: 'いちども', translation: 'Ninguna vez, nunca' },
  { kanji: '段々', kana: 'だんだん', translation: 'Gradua lmente' },
  { kana: 'もうすぐ', translation: 'Pronto' },
  { kana: 'おかげさまで', translation: 'Gracias  (se usa' },
  { kanji: '乾杯', kana: 'かんぱい', translation: 'Salud' },
  { kana: 'じつは', translation: 'De hecho , a decir' },
  { kana: 'ダイエット', translation: 'Dieta' },
  { kana: 'なんかいも', translation: 'Muchas veces  漢字  ひらがな  カタカナ  Español' },
  { kana: 'しかし', translation: 'Pero, sin e mbargo' },
  { kana: 'からだにいい', translation: 'Bueno para la salud' },
  { kana: 'ケーキ', translation: 'Doctor (utilizado' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'おもいます', translation: 'Creer/Pensar .' },
  { kana: 'いいます', translation: 'Decir .' },
  { kana: 'かちます', translation: 'Ganar .' },
  { kana: 'まけます', translation: 'Perder (el partido,' },
  { kana: 'す', translation: '［おまつり が］' },
  { kana: 'あります', translation: 'Haber , tener ,' },
  { kana: 'やくにたちます', translation: 'Ser útil.' },
  { kana: 'うごきます', translation: 'Funcionar, moverse .' },
  { kana: 'きをつけます', translation: 'Presta atención ,' },
  { kana: 'りゅうがくします', translation: 'Estudiar en el' },
  { kana: 'すごい', translation: 'Terrible, maravilloso' },
  { kanji: '本当', kana: 'ほんとう', translation: 'Verdad .' },
  { kanji: '嘘', kana: 'うそ', translation: 'Mentira .' },
  { kanji: '自動車', kana: 'じどうしゃ', translation: 'Automóvil , coche .' },
  { kanji: '交通', kana: 'こうつう', translation: 'Transpo rte, trafico .' },
  { kanji: '放送', kana: 'ほうそう', translation: 'Transmisión , anuncio.' },
  { kana: 'ニュース', translation: 'Noticia.' },
  { kana: 'アニメ', translation: 'Comic/caricatura.' },
  { kana: 'デザイン', translation: 'Diseño.' },
  { kanji: '夢', kana: 'ゆめ', translation: 'Sueño.' },
  { kanji: '天才', kana: 'てんさい', translation: 'Genio.' },
  { kanji: '地球', kana: 'ちきゅう', translation: 'Tierra.' },
  { kanji: '月', kana: 'つき', translation: 'Luna.' },
  { kana: 'きっと', translation: 'Sin falta.  漢字  ひらがな  カタカナ  Español' },
  { kanji: '最近', kana: 'さいきん', translation: 'Últimamente , estos' },
  { kanji: '多分', kana: 'たぶん', translation: 'Probablemente,' },
  { kana: 'ほんとうに', translation: 'Realmente.' },
  { kana: 'そんなに', translation: 'No tan  (se emplea' },
  { kana: 'ひさしぶりですね', translation: '。  ¡Tanto tiempo sin' },
  { kanji: '勿論', kana: 'もちろん', translation: 'Naturalmente, p or' },
  { kana: 'もうかえらない', translation: '…  Tengo que irme ya …' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'きます', translation: 'Ponerse (una camisa,' },
  { kana: 'はきます', translation: 'Ponerse (zapatos,' },
  { kana: 'がぶります', translation: 'Ponerse (un' },
  { kana: 'かけます', translation: 'Ponerse  (las gafas ,' },
  { kana: 'します', translation: 'Ponerse (la corbata) .' },
  { kana: 'うまれま', translation: 'す  Nacer.' },
  { kana: 'コート', translation: 'Abrigo .' },
  { kana: 'スーツ', translation: 'Traje.' },
  { kana: 'セーター', translation: 'Suéter .' },
  { kanji: '帽子', kana: 'ぼうし', translation: 'Sombrero.' },
  { kanji: '眼鏡', kana: 'めがね', translation: 'Anteojos, lentes.' },
  { kana: 'ケーキ', translation: 'Torta, Pastel.' },
  { kana: 'ロボット', translation: 'Robot.' },
  { kana: 'ユーモア', translation: 'Humor.' },
  { kanji: '都合', kana: 'つごう', translation: 'Conv eniencia.' },
  { kana: 'よく', translation: 'Frecuentemente.' },
  { kana: 'えーと', translation: 'Bueno, veamos.' },
  { kana: 'おめでとう', translation: '[ございま す]  ¡Felicitacion es!' },
  { kanji: '家賃', kana: 'やちん', translation: 'Alquiler de casa .' },
  { kana: 'ダイニング', translation: 'キチン Cocina, comedor.' },
  { kana: 'では', translation: 'Veamos , bueno .' },
  { kanji: '和室', kana: 'わしつ', translation: 'Habitación  de estilo' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'おしいれ', translation: 'Armario de estilo' },
  { kanji: '布団', kana: 'ふとん', translation: 'Futón  (se usa tanto' },
  { kana: 'アパート', translation: 'Apartame nto.' },
  { kana: 'パリ', translation: 'Paris.' },
  { kanji: '長城', kana: 'ばんりのちょうじょう', translation: 'La gran mur alla china.' },
  { kana: 'アンケート', translation: 'Encuesta.' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'ききます', translation: 'Escuchar  (al profesor).' },
  { kana: 'まわします', translation: 'Girar.' },
  { kana: 'ひきます', translation: 'Tirar, jalar.' },
  { kana: 'かえます', translation: 'Cambiar.' },
  { kana: 'さわります', translation: 'Tocar (una puerta).' },
  { kana: 'でます', translation: '［おつりが ～］' },
  { kana: 'でます', translation: 'Salir  (el cambio ).' },
  { kana: 'あるきます', translation: 'Caminar.' },
  { kana: 'わたります', translation: 'Cruzar un puente.' },
  { kana: 'まがります', translation: 'Doblar, girar (a la' },
  { kana: 'さびしい', translation: 'Solitario.' },
  { kanji: '音', kana: 'おと', translation: 'Sonido.' },
  { kana: 'サイズ', translation: 'Tamaño, talla.' },
  { kanji: '故障', kana: 'こしょう', translation: 'Avería .' },
  { kanji: '道', kana: 'みち', translation: 'Calle, camino.' },
  { kanji: '交差点', kana: 'こうさてん', translation: 'Cruce.' },
  { kanji: '信号', kana: 'しんごう', translation: 'Semáforos .' },
  { kanji: '角', kana: 'かど', translation: 'Esquina.' },
  { kanji: '橋', kana: 'はし', translation: 'Puente.' },
  { kanji: '駐車場', kana: 'ちゅうしゃじょう', translation: 'Estacionamiento.' },
  { kanji: '建物', kana: 'たてもの', translation: 'Edificio.' },
  { kana: 'なんかいも', translation: 'Muchas veces.' },
  { kanji: '聖徳太子', kana: 'しょうとくたいし', translation: 'Príncipe Shotoku (574' },
  { kanji: '法隆寺', kana: 'ほうりゅうじ', translation: 'Horyuji (templo' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'くれます', translation: 'Dar (a mí).' },
  { kana: 'なおします', translation: 'Reparar, arreglar,' },
  { kana: 'つれていきます', translation: 'Llevar (a alguien).' },
  { kana: 'つれてきます', translation: 'Traer (a alguien).' },
  { kana: 'おくります', translation: 'Acompañar, llevar (a' },
  { kana: 'しょうかいします', translation: 'Presentar (a alguien).' },
  { kana: 'せつめいします', translation: 'Guía por (una ciudad,' },
  { kana: 'おじいさん', translation: 'おじいちゃん   Explicar.' },
  { kana: 'おばあさん', translation: 'おばあちゃん   Abuelo, anciano.' },
  { kanji: '旬美', kana: 'しゅんび', translation: 'Preparación.' },
  { kana: 'ひっこし', translation: 'ひっこし   Mudanza.' },
  { kana: 'ホームステイ', translation: 'Hospedaje en casa de' },
  { kanji: '全部', kana: 'ぜんぶ', translation: 'Todo.' },
  { kana: 'じぶんで', translation: 'Solo.' },
  { kana: 'ほかに', translation: 'Además, parte.' },
  { kanji: '日', kana: 'ははのひ', translation: 'Dia de la Madre.' },
  { kanji: '漢字', kana: 'ひらがな', translation: 'カタカナ  Español' },
  { kana: 'かんがえます', translation: 'Pensar, considerar.' },
  { kana: 'つきます', translation: 'Llegar.' },
  { kana: 'とります', translation: 'Envejecer.' },
  { kana: 'たります', translation: 'Ser suficiente.' },
  { kanji: '田舎', kana: 'いなか', translation: 'Zona rural, pueblo' },
  { kana: 'チャンス', translation: 'Chance, oportunidad.' },
  { kanji: '億', kana: 'おく', translation: 'Cien millones.' },
  { kana: 'もしもし', translation: 'Hola, aló (usado para' },
  { kanji: '転勤', kana: 'てんきん', translation: 'Traslado.' },
  { kana: 'こと', translation: 'Cosa, asunto ( ～のこ' },
  { kanji: '暇', kana: 'ひま', translation: 'Tiempo libre.' },
  { kana: 'おせわになりました', translation: 'Muchas gracias por' },
  { kana: 'かんばります', translation: 'Esforzarse, tener' },
  { kana: 'どうぞお', translation: '元気で どうぞおげんきで   Que siga bien/Que le' }
]
